### ISSUE TITLE
dr_mp3: Expression is always true.

### ISSUE THREAD

**Issue by krcroft** [mackron/dr_libs#101]
![image](https://user-images.githubusercontent.com/1557255/72753952-34bc6700-3b7b-11ea-85d5-44d934b7d6ee.png)

https://www.viva64.com/en/w/v547/

**Comment by mackron** [comment]
This is a legitimate bug. Fixed here: https://github.com/mackron/dr_libs/commit/dcaea5403fa7a81bd1f148717cb25fc16dd7e3f9
