### ISSUE TITLE
dr_mp3: Expression is always false.

### ISSUE THREAD

**Issue by krcroft** [mackron/dr_libs#102]
![image](https://user-images.githubusercontent.com/1557255/72753972-53226280-3b7b-11ea-9663-d99b2e6c3861.png)

https://www.viva64.com/en/w/v547/

**Comment by mackron** [comment]
Only in the 64-bit case, but still a valid check for 32-bit. Will not fix.

**Comment by krcroft** [comment]
Thanks for the quick assessment on these @mackron.

I will create ignore rules for these specific statements in a project-wide `.pvsconfig` file for `dosbox-staging`.  Should be valid for `dr_libs` too, if you want to provide that to other users so they can avoid hitting false-positives.
