### ISSUE TITLE
dr_wav: pointers are cast to a more strictly aligned pointer type.

### ISSUE THREAD

**Issue by krcroft** [mackron/dr_libs#103]
![image](https://user-images.githubusercontent.com/1557255/72754006-78af6c00-3b7b-11ea-9766-03eb80eae0ce.png)

https://www.viva64.com/en/w/v1032/

**Comment by mackron** [comment]
Fixed: https://github.com/mackron/dr_libs/commit/31d9578fb6a06d9729aab12a5872507fe5c1b44d
