### ISSUE TITLE
dr_wav: Expression 'bytesToWrite > (18446744073709551615UL)' is always false.

### ISSUE THREAD

**Issue by krcroft** [mackron/dr_libs#105]
![image](https://user-images.githubusercontent.com/1557255/72754222-13a84600-3b7c-11ea-9ebc-5ee5e8aad1c4.png)

https://www.viva64.com/en/w/v547/

**Comment by mackron** [comment]
Only in the 64-bit case, but still a valid check for 32-bit. Will not fix.
