### ISSUE TITLE
dr_wav: Expression 'bytesToWrite > (18446744073709551615UL)' is always false.

### ISSUE THREAD

**Issue by krcroft** [mackron/dr_libs#106]
![image](https://user-images.githubusercontent.com/1557255/72754267-2e7aba80-3b7c-11ea-8022-db272a37e3e5.png)

https://www.viva64.com/en/w/v547/

**Comment by mackron** [comment]
Only in the 64-bit case, but still a valid check for 32-bit. Will not fix.
