### ISSUE TITLE
Opus decoder.

### ISSUE THREAD

**Issue by ghost** [mackron/dr_libs#11]
Was just wondering if its possible that a one-file Opus decoder can be made.

**Comment by mackron** [comment]
I've considered it, but I don't have an immediate need for it myself, and with my current workload it's a bit hard to find the time. I have, however, been considering doing a video playback library which will require support for Opus for completeness (and a video decoder for that matter) so it may happen at some point.

If enough people want it though, I might be able to be convinced to rearrange my schedule and get it done.

There's also [this to consider](http://nothings.org/stb/stb_opus.html), but I reckon I could figure something out there...
