### ISSUE TITLE
dr_wav: The condition 'bytesPerFrame > 0' of loop is always true.

### ISSUE THREAD

**Issue by krcroft** [mackron/dr_libs#110]
![image](https://user-images.githubusercontent.com/1557255/72754422-916c5180-3b7c-11ea-9d73-a22988e931f1.png)

https://www.viva64.com/en/w/v654/

**Comment by mackron** [comment]
This was an actual bug. Thanks! Fixed in the dev branch: https://github.com/mackron/dr_libs/commit/73e0fa1204a96709ce11095e106b74585513ad37

**Comment by krcroft** [comment]
Hey.. finally some bang-for-our-buck on this analysis round!
Thank you for the fixes Dave.
