### ISSUE TITLE
dr_mp3: The 'result' variable was assigned the same value.

### ISSUE THREAD

**Issue by krcroft** [mackron/dr_libs#118]
![image](https://user-images.githubusercontent.com/1557255/72756433-0f7f2700-3b82-11ea-9894-cffaba9575e5.png)

https://www.viva64.com/en/w/v1048/

**Comment by mackron** [comment]
This is C++ code and not part of dr_mp3.

**Comment by krcroft** [comment]
Sorry Dave, oops, that one's over in my code! (will fix this with an assert)
