### ISSUE TITLE
Draft FLAC (dev) struct size ordering (tiny size optimization)

### ISSUE THREAD

**Issue by kcgen** [mackron/dr_libs#122]
This has existed for a while, but am just posting it now.  Absolute non-issue, but nice to have if you're updating the code.

![2020-03-28_21-47](https://user-images.githubusercontent.com/1557255/77840646-7bf84280-713e-11ea-9e8e-55641dd1ddad.png)

**Comment by mackron** [comment]
Setting this one to wont fix. I like the order of members in these structures to map with the structure of the actual data and with the definition of the block in the spec. The drflac_metadata structure doesn't need to be super tightly packed - it's not like anybody is going to packing many drflac_metadata instantiations where it'll matter.
