### ISSUE TITLE
Assert triggered on seek (targetByte >= rangeLo), referenced issue

### ISSUE THREAD

**Issue by kcgen** [mackron/dr_libs#124]
Referenced issue: https://github.com/dreamer/dosbox-staging/issues/269

Seeking inside this truncated file: [cd.zip](https://github.com/dosbox-staging/dosbox-staging/files/4434562/cd.zip)

**Comment by mackron** [comment]
This should be fixed in https://github.com/mackron/dr_libs/commit/eaa125cc191e0047e4ba9aab7c59524fc326f504

See here for explanation: https://github.com/dosbox-staging/dosbox-staging/issues/269#issuecomment-609677734

**Comment by kcgen** [comment]
Thanks @mackron!
