### ISSUE TITLE
`drmp3__malloc_from_callbacks` not found

### ISSUE THREAD

**Issue by Clownacy** [mackron/dr_libs#125]
`drmp3__malloc_from_callbacks` is wrapped in an `#ifndef DR_MP3_NO_STDIO`, but apparently the function is now used even when `DR_MP3_NO_STDIO` is defined, causing an error.

**Comment by mackron** [comment]
Thanks for the report. I actually just fixed this the other day: https://github.com/mackron/dr_libs/commit/cfc9a39178e6f2349ce28ca5c09a93217b680957. Note that the recent 0.6.x iteration has some breaking API changes if you haven't already updated.
