### ISSUE TITLE
__int8 and __int64 errors in VC6

### ISSUE THREAD

**Issue by Clownacy** [mackron/dr_libs#134]
VC6 has a weird bug, where it gives an error when it tries to convert an `unsigned __int8` to an `unsigned char`. This is a problem across dr_wav, dr_flac, and dr_mp3.

In addition, dr_wav triggers an error about an `unsigned __int64` being converted to a `double`:
```c
drwav_uint64 targetDataSizeBytes = (drwav_uint64)(totalSampleCount * pFormat->channels * pFormat->bitsPerSample/8.0);
```

This can be worked-around by casting `totalSampleCount` to `drwav_int64`.

**Comment by mackron** [comment]
Are you able to post the `unsigned __int8/char` errors? Just not sure where it is I'm supposed to be looking. I wonder if I should instead do `typedef unsigned char drwav_uint8` instead of `typedef unsigned __int8 drwav_uint8`? Also, I'm not seeing those errors...

I've pushed a fix for the `__int64` issue to the dev branch: https://github.com/mackron/dr_libs/commit/9338d618dee1d0c2042cfeb4c02d23cf65da5411

**Comment by Clownacy** [comment]
Changing them to `typedef unsigned char drwav_uint8` was what I did.

Here's an error message:
```
C:\Users\Clownacy\Desktop\clownaudio\src\decoding\decoders\libs/dr_mp3.h(2193) :
 error C2664: 'drmp3_hdr_frame_bytes' : cannot convert parameter 1 from 'const u
nsigned char *' to 'const unsigned __int8 *'
        Types pointed to are unrelated; conversion requires reinterpret_cast, C-
style cast or function-style cast
```

Since it's clearly a bug, I imagine it was fixed in one of VC6's service packs. My installation doesn't have any of those. I'm fine with upgrading, if you want to make it a hard requirement.

**Comment by kcgen** [comment]
Yeah, that's looks like a bug on the compiler's side; good catch @Clownacy.  I agree that it's best to keep the code compliant and sane, and go with the latest/patched release of compiler if you can. (just my opinion as a happy user of dr_libs) :-)

**Comment by mackron** [comment]
All of my single file audio libraries have the philosophy of just working, regardless of compiler. Are all the errors related to pointer conversions? In that specific error, I'm of the opinion that the better solution is to change the parameter of `drmp3dec_decode_frame()` from `unsigned char*` to `drmp3_uint8*` if only to keep it clean and consistent. I'm not getting those errors, though, so I'll need a full list before I can do anything practical. I've pushed a fix for that specific error in dr_mp3, and I think that should be clean now (at least, there's no more references to `unsigned char` that I can see).

**Comment by Clownacy** [comment]
Yes, they all seem to be related to pointers:
```
C:\Users\Clownacy\Desktop\clownaudio\src\decoding\decoders\libs/dr_flac.h(2822)
: error C2664: 'drflac__read_uint8' : cannot convert parameter 3 from 'unsigned
char [7]' to 'unsigned __int8 *'
        Types pointed to are unrelated; conversion requires reinterpret_cast, C-
style cast or function-style cast
C:\Users\Clownacy\Desktop\clownaudio\src\decoding\decoders\libs/dr_flac.h(2857)
: error C2664: 'drflac__read_uint8' : cannot convert parameter 3 from 'unsigned
char *' to 'unsigned __int8 *'
        Types pointed to are unrelated; conversion requires reinterpret_cast, C-
style cast or function-style cast
C:\Users\Clownacy\Desktop\clownaudio\src\decoding\decoders\libs/dr_flac.h(4753)
: error C2664: 'drflac__read_uint8' : cannot convert parameter 3 from 'unsigned
char *' to 'unsigned __int8 *'
        Types pointed to are unrelated; conversion requires reinterpret_cast, C-
style cast or function-style cast
C:\Users\Clownacy\Desktop\clownaudio\src\decoding\decoders\libs/dr_flac.h(4845)
: error C2664: 'drflac__read_uint8' : cannot convert parameter 3 from 'unsigned
char *' to 'unsigned __int8 *'
        Types pointed to are unrelated; conversion requires reinterpret_cast, C-
style cast or function-style cast
C:\Users\Clownacy\Desktop\clownaudio\src\decoding\decoders\libs/dr_flac.h(5323)
: error C2664: 'drflac__read_uint8' : cannot convert parameter 3 from 'unsigned
char *' to 'unsigned __int8 *'
        Types pointed to are unrelated; conversion requires reinterpret_cast, C-
style cast or function-style cast
C:\Users\Clownacy\Desktop\clownaudio\src\decoding\decoders\libs/dr_flac.h(8508)
: error C2440: '=' : cannot convert from 'const unsigned char *' to 'const unsig
ned __int8 *'
        Types pointed to are unrelated; conversion requires reinterpret_cast, C-
style cast or function-style cast
C:\Users\Clownacy\Desktop\clownaudio\src\decoding\decoders\libs/dr_flac.h(8539)
: error C2440: '=' : cannot convert from 'const unsigned char *' to 'const unsig
ned __int8 *'
        Types pointed to are unrelated; conversion requires reinterpret_cast, C-
style cast or function-style cast
```

```
C:\Users\Clownacy\Desktop\clownaudio\src\decoding\decoders\libs/dr_wav.h(1589) :
 error C2664: 'drwav__fourcc_equal' : cannot convert parameter 1 from 'unsigned
__int8 [4]' to 'const unsigned char *'
        Types pointed to are unrelated; conversion requires reinterpret_cast, C-
style cast or function-style cast
```

**Comment by mackron** [comment]
Thanks for that. I ended up just doing a find and replace on all occurrences of `unsigned char` which I think should clean these errors up. In the dev branch. Are you able to try that out for me?

**Comment by Clownacy** [comment]
Looks like that fixed it. Thanks a lot.

**Comment by mackron** [comment]
Thanks for testing that for me. I'll get these changes released soon.
