### ISSUE TITLE
Read/Write markers from Wave

### ISSUE THREAD

**Issue by Nowhk** [mackron/dr_libs#135]
Hi,

is it possible to read/write raw data from wave? 
I need to read/write markers, stored on file.

Otherwise, not sure how to flag this issue as "feature-request" :)

Thanks, as usual!

**Comment by kcgen** [comment]
Hi @Nowhk ; can you describe in more detail what you're trying to do?

**Comment by Nowhk** [comment]
@kcgen when I open a wave that contains markers within an Editor, it show to me them. 

Example here, using IL Edison:

![image](https://user-images.githubusercontent.com/19835752/80606329-7be8ac80-8a34-11ea-8d23-e8a558412c1e.png)
As you can see, marker sections are yellow, while red ones are loop section.

I'd like to display them on my plugin.

**Comment by kcgen** [comment]
Thanks @Nowhk; sorry - I will let @mackron take it from here :-).  I accidentally got confused that this issue was submitted in our `dosbox-staging` repo; argh. sorry; too early here!

**Comment by mackron** [comment]
The short answer is that you can read them, but you cannot (currently) write them.

The long answer depends on a few things before I can give good advice. Are these cue points? As in, are they the "cue " chunk from here: https://sites.google.com/site/musicgapi/technical-documents/wav-file-format? My suspicion is these are done as "cue " chunks combined with "note" chunks for the labels. To read these you would need to call the the `_ex` variants of `drwav_init*`. These allow you to pass in a callback that will be called for every chunk, which will then give you the ability to handle the chunk yourself. See documentation for the chunk callback here: https://github.com/mackron/dr_libs/blob/master/dr_wav.h#L420.

There is currently no way to write custom chunks using the built-in writing API. I can probably add an API for writing custom chunks, though.

**Comment by mackron** [comment]
Thinking about this a bit more, I can probably add some helper APIs to make it easier to read and write cue points and labels. I've had requests for reading cue points before. The reason they aren't loaded as part of `drwav_init()` is that they're of an arbitrary size and I want to avoid heap allocations.

**Comment by Nowhk** [comment]
Yes, an helper API would be fancy. So I can load/write them "when I want", not every time I open a wave. Let me/us know :P

**Comment by mackron** [comment]
I'm not going to add an internal heap allocated buffer to the `drwav` object for cue points as I want to avoid heap allocations in `drwav_init()` and family. When loading, the way it would work is you would handle it in the `onChunk` callback that you pass in to the `_ex()` variant of `drwav_init*()` which you do once at load time for each wav file you load. From there you can do whatever you want with the data, so long as you abide by the rules set out in the documentation for the chunk callback that I linked earlier. My suggestion was to perhaps add some helper APIs just to make it easier to handle cue points in the `onChunk` callback is all - you'll still need to manage the cue points yourself. It's not going to be elegant, but it's a _way_ of handling cue points by your application, albeit untidily.

For writing, the API doesn't exist yet and I still haven't decided how I want to do it. I'll leave this issue open and let you know what I decide to do, though.

**Comment by Nowhk** [comment]
I don't use drwav_init, but drwav_open_file_and_read_pcm_frames_f32. Can I perform the same task?

**Comment by mackron** [comment]
No, `drwav_open_file_and_read_pcm_frames_f32()` won't work. That's just a high level helper API for quickly reading the audio data and was never designed for advanced stuff like parsing cue points.

**Comment by mackron** [comment]
The latest version of dr_wav includes a function to write metadata: `drwav_init_write_with_metadata()`. See documentation on usage.
