### ISSUE TITLE
dr_wav: assert() used instead of DRWAV_ASSERT()

### ISSUE THREAD

**Issue by JoyeuxCodeur** [mackron/dr_libs#136]
Hello,
In dr_wav.h, in drwav_bool32 drwav_seek_to_pcm_frame(), you use assert() instead of DRWAV_ASSERT()
Regards

**Comment by mackron** [comment]
Thanks for the report. Good catch! Fixed in the dev branch.

Commit: https://github.com/mackron/dr_libs/commit/5e5dea856c2da73c28c18ef5365772e91b00343d

**Comment by mackron** [comment]
This has been released.
