### ISSUE TITLE
Add API with version/copyright/left information in all libs (#define VERSION, const char* drwav_version(), etc)

### ISSUE THREAD

**Issue by diegoefe** [mackron/dr_libs#137]

**Comment by mackron** [comment]
I did this just recently in miniaudio so I'm happy to add this. Will update this issue once I've got it done.

**Comment by diegoefe** [comment]
Excellent!
Thanks!

**Comment by mackron** [comment]
This has been added:

dr_flac: d8fc485fbcb8c9956e1369d81a4d8d4ff68abc4a
dr_wav: 623fdd9d1bcac79ecc062bee6862ca8ce5c5a8c1
dr_mp3: 2f7e16d67703a6a7478238e866037b6cbacf03f0
