### ISSUE TITLE
Potential use of uninitialized info struct members

### ISSUE THREAD

**Issue by kcgen** [mackron/dr_libs#138]
On line 2753, if `drmp3dec_decode_frame(...)` doesn't read any frames then we should avoid reading the `info` struct members `.channels` and `.hz`, which will not have been populated.

``` c++
    pcmFramesRead = drmp3dec_decode_frame(... , &info);
    ...
    pMP3->mp3FrameChannels             = info.channels;
    pMP3->mp3FrameSampleRate           = info.hz;
```

A similar chunk of code is further up on line 2695, which does include protection: 

``` c++
    pcmFramesRead = drmp3dec_decode_frame(..)

    /* pcmFramesRead will be equal to 0 if decoding failed. If it is zero and info.frame_bytes > 0 then we have successfully decoded the frame. */
    if (pcmFramesRead > 0) {
        ...
        pMP3->mp3FrameChannels = info.channels;
        pMP3->mp3FrameSampleRate = info.hz;
        ....
```

**Comment by mackron** [comment]
Thanks. Potential fix in the dev branch: https://github.com/mackron/dr_libs/commit/a869f49fd74127c2faf524c5bd6677f3061115e4

**Comment by kcgen** [comment]
That solved it; thank you @mackron !

**Comment by mackron** [comment]
Thanks for testing. Pushed to the master branch and bumped the version.

**Comment by kcgen** [comment]
It's in the mix; thanks!
