### ISSUE TITLE
drmp3_read_pcm_frames_f32 doesn't properly advance the output buffer when converting from s16 to float

### ISSUE THREAD

**Issue by camlorn** [mackron/dr_libs#141]
At the bottom of the loop in this function when converting from `drmp3_int16` you have:

```
drmp3_s16_to_f32((float*)DRMP3_OFFSET_PTR(pBufferOut, sizeof(drmp3_int16) * totalPCMFramesRead * pMP3->channels), pTempS16, framesJustRead * pMP3->channels);
```

Which advances it as if the output buffer is a buffer of int16.  The effect is that reading any value that needs to advance this loop more than once causes it to overwrite data instead of fully filling the buffer.  I've patched my local copy to be:

```
drmp3_s16_to_f32((float*)DRMP3_OFFSET_PTR(pBufferOut, sizeof(float) * totalPCMFramesRead * pMP3->channels), pTempS16, framesJustRead * pMP3->channels);
```

Which appears to work, but I'm not sure if that's right.  Also I'm not set up to run the tests.

**Comment by camlorn** [comment]
As a clarification: you have to use very large frame counts to hit this bug.  Specifically (in my case) stereo works up to a frame count of 4096, then fails because 4097 runs the loop twice.

**Comment by mackron** [comment]
Thanks for the report! You're correct. I've fixed this in the dev branch and will get this released to the master branch soon. Are you able to verify that's working for you?

Commit: https://github.com/mackron/dr_libs/commit/43fffdbb9301bee5c7a02dbe4105bac7b7267b94

**Comment by camlorn** [comment]
yep, sure is.  Thanks!

**Comment by mackron** [comment]
Thanks for confirming that for me. This has been released.
