### ISSUE TITLE
dr_flac: drflac__seek_to_approximate_flac_frame_to_byte gets stuck in an infinite loop

### ISSUE THREAD

**Issue by G4Vi** [mackron/dr_libs#150]
`drflac__seek_to_approximate_flac_frame_to_byte` has no safety check to break out after `rangeLo` and `rangeHi`  converge to the same value and seek fails. It continues endlessly attempting to use the same targetByte as it can no longer change after `rangeLo == RangeHi`. 

This can happen when the seek callback continuously returns DRFLAC_FALSE (such as on IO errors).

**Comment by mackron** [comment]
That pull request has been merged. Thanks!
