### ISSUE TITLE
dr_flac question: totalPCMFrameCount, exact or padded?

### ISSUE THREAD

**Issue by kcgen** [mackron/dr_libs#152]
This was pointed out in a forum:

> like all codecs (FLAC) still has a minimum framesize so if the total number of samples is not an exact multiple of that amount, padding gets added. The actual number of samples contained in the final block is stored in the FLAC headers but unfortunately not handled by the core decoder (libflac) and left up to the calling application to deal with, which unfortunately SDL_Sound neglects to do...

> So tracks gets padded with extra samples, and due to the nature of cue sheets this causes each successive track to get increasingly shifted away from their original start time.

Does dr_flac's `totalPCMFrameCount` provide the exact original PCM frame count stored in the flac header or the padded count?

Much thanks @mackron!

**Comment by mackron** [comment]
The `totalPCMFrameCount` variable is taken straight from the STREAMINFO header. From `drflac__init_private__native()`:

```c
pInit->totalPCMFrameCount      = streaminfo.totalPCMFrameCount;
```

If the length is unknown, it's set to 0 (will happen with things like internet streams).

With `drflac_read_pcm_frames_*()`, dr_flac will read as many samples are advertised on a per-frame basis. So if the padded samples are advertised in the sample count of the header for that frame, they'll be returned. The `totalPCMFrameCount` member of the `drflac` structure will not be used as a clamp in this function. If you were wanting to clamp against `totalPCMFrameCount`, you would need to keep track of a counter and use that in conjunction with `totalPCMFrameCount` to clamp the number of samples you try reading. Seeking, however, *does* need to use `totalPCMFrameCount` in order to avoid out-of-bounds seeking.

Where is this thread? I actually thought SDL_Sound was using dr_flac, but I could be thinking of something else. My decoding test uses libflac as a benchmark which, if I'm reading it correctly right now, should catch any discrepancies between the two, which you can see here: https://github.com/mackron/dr_libs/blob/master/tests/flac/dr_flac_decoding.c#L19-L26

**Comment by kcgen** [comment]
Thanks for the thorough and quick response Dave.

The thread is here: https://www.vogons.org/viewtopic.php?p=904567#p904567

Given your decoding tests, both dr_flac and libflac appear to be getting the exact frames (matching with the STREAMINFO header); so the statement itself sounds incorrect.

SDL_Sound 1.2 in theory uses libFLAC, however its broken and has never worked with DOSBox, which is where this discussion comes from.

But you're right regarding DOSBox and FLAC audio: the only DOSBoxes capable of reading FLAC tracks all use my CDDA patch, which indeed uses `dr_flac` and not `libflac`.

So my guess is this Vogon's post is speaking in hypothetical terms, given there are no dosboxes even using libflac.

**Comment by mackron** [comment]
Well the spec does indeed mention that that minimum sample count per FLAC frame is 16, so the poster is right about that part. It's more a question of whether or not any encoder will ever set the total sample count in the STREAMINFO header to *not* include the padding samples. I don't have any evidence one way or the other (probably wouldn't be too hard to write an automated program to check that against my test vectors). In my mind I want to say that it'd be strange that the STREAMINFO sample count wouldn't match up with the padded count, but on the other hand it would be useful to know the exact sample count of the original sound, so maybe it doesn't include padding. Not entirely sure without looking at the libFLAC encoder source, I suppose. Certainly the spec doesn't explicitly mention anything about it.

This commit is what I saw regarding SDL_Sound + dr_flac, by the way. No idea if this change ever made it into a release. https://hg.icculus.org/icculus/SDL_sound/rev/1aea203b6c39

**Comment by kcgen** [comment]
Ahh - nice! Looks like plans were (are) afoot to use dr_flac in SDL_Sound 2.x, whenever they get around to getting it all in working order. 

>  it would be useful to know the exact sample count of the original sound, so maybe it doesn't include padding. 

Yes, for me as a user, I only want to operate on the set of original encoded PCM samples. If that's 100 samples, than I want to be given the appearance that the encoded file only has 100 samples, and I can seek within them, and onle 100 samples will play.

If we take the argument to the extreme - image an insane codec that include 5 MiB of front-padding,  some number of inter-packet padding, and finally another 10 MiB of padding at the back.  However insane all that is, I only want to operate on the original data I gave it to represent. I want all of it's internal baggage hidden from me.

**Comment by kcgen** [comment]
> I don't have any evidence one way or the other (probably wouldn't be too hard to write an automated program to check that against my test vectors).

Knowing this would be very valuable.

If `totalPCMFrameCount` includes FLAC-specific padding frames, then I would prefer some way to back-out those extraneous frames (be it another call to determine the padding, which I can subtract, or perhaps:
 - `totalPaddedPCMFrameCount`
 - `totalOriginalPCMFrameCount`

**Comment by kcgen** [comment]
WAV duration compared with meta FLAC's total-samples are all in agreement:

**mediainfo ../wav/track46.wav**: `Duration: 43 s 986 ms

**metaflac --show-total-samples ../flac/track46.flac**: `1939812`

``` text
[04:07:02@hoya audio] python
Python 2.7.18 (default, Aug  4 2020, 11:16:42) 
[GCC 9.3.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> 1939812 / 44100.
43.986666666666665
```

**Comment by mackron** [comment]
I actually forgot about this one - are we happy with this, and can I close this ticket?

**Comment by kcgen** [comment]
Yes; from my testing I'm getting the exact length back from dr_flac, which is perfect.  Closing.
