### ISSUE TITLE
dr_wav: logic inference, flagged by PVS Studio

### ISSUE THREAD

**Issue by kcgen** [mackron/dr_libs#153]
![2020-11-10_11-32](https://user-images.githubusercontent.com/1557255/98725414-f1212c80-2349-11eb-8b64-317d8c97b817.png)

Full report attached (extract, enter the '**general**' directory, open **index.html**:

[pvs-analysis-report.zip](https://github.com/mackron/dr_libs/files/5519812/pvs-analysis-report.zip)

**Comment by kcgen** [comment]
I'm not sure if this is correct, but PVS's insights can sometimes point out order-of-operations changes that might read more naturally. 

For example, maybe sampleCountFromFactChunk could be moved after the seek (unless its some kind of global variable that's used by the seek function).

**Comment by mackron** [comment]
I'm setting this one to Will Not Fix. I just don't understand why on Earth PVS would be suggesting that `sampleCountFromFactChunk` may want to be used inside `drwav__seek_forward()` - that makes no sense at all. In any case, I'm happy with the logic flow and I don't think there's anything needing to be changed.

**Comment by kcgen** [comment]
Thanks for the quick assessment!

**Comment by kcgen** [comment]
For those who might also hit this in PVS, the following suppression can be used:
``` json
        {
            "CodeCurrent": 1849716353,
            "CodeNext": 11359373,
            "CodePrev": 2663124891,
            "ErrorCode": "V1051",
            "FileName": "dr_wav.h",
            "Message": "Consider checking for misprints. It's possible that the 'sampleCountFromFactChunk' should be used inside 'drwav__seek_forward' function."
        },
```
