### ISSUE TITLE
dr_wav: potential bit-shifting of garbage value, flagged by static Clang analyzer

### ISSUE THREAD

**Issue by kcgen** [mackron/dr_libs#161]
![2020-11-10_11-38](https://user-images.githubusercontent.com/1557255/98725957-ace25c00-234a-11eb-8382-992682458049.png)

Full report attached:

[clang-analysis-report.zip](https://github.com/mackron/dr_libs/files/5519836/clang-analysis-report.zip)

**Comment by mackron** [comment]
https://github.com/mackron/dr_libs/issues/155
