### ISSUE TITLE
dr_wav: potential bit-shifting of garbage value, flagged by static Clang analyzer

### ISSUE THREAD

**Issue by kcgen** [mackron/dr_libs#164]
![2020-11-10_11-39](https://user-images.githubusercontent.com/1557255/98725981-b66bc400-234a-11eb-96d7-c20c242e82a2.png)

Full report attached:

[clang-analysis-report.zip](https://github.com/mackron/dr_libs/files/5519836/clang-analysis-report.zip)

**Comment by mackron** [comment]
Related to https://github.com/mackron/dr_libs/issues/155
