### ISSUE TITLE
dr_mp3: potential passing of unexpected null pointer, flagged by static Clang analyzer

### ISSUE THREAD

**Issue by kcgen** [mackron/dr_libs#165]
![2020-11-10_11-39_1](https://user-images.githubusercontent.com/1557255/98725985-b966b480-234a-11eb-836e-83fb2875498d.png)

Full report attached:

[clang-analysis-report.zip](https://github.com/mackron/dr_libs/files/5519836/clang-analysis-report.zip)

**Comment by mackron** [comment]
I think this is also a false positive. I've added some asserts to hopefully help the analyzer. Commit: https://github.com/mackron/dr_libs/commit/ba7f3179833e02d0d1167b07c9ef721dec70ad92

**Comment by kcgen** [comment]
This worked perfectly, thank you @mackron. **dr_mp3** is now running clean through the latest PVS and Clang analyzers. :+1:
