### ISSUE TITLE
dr_wav: potential use of uninitialized argument, flagged by static Clang analyzer

### ISSUE THREAD

**Issue by kcgen** [mackron/dr_libs#166]
![2020-11-10_11-39_2](https://user-images.githubusercontent.com/1557255/98725996-bc61a500-234a-11eb-8471-06884bdb75ca.png)

Full report attached:

[clang-analysis-report.zip](https://github.com/mackron/dr_libs/files/5519836/clang-analysis-report.zip)

**Comment by mackron** [comment]
Related to https://github.com/mackron/dr_libs/issues/155
