### ISSUE TITLE
Writing 24-bit WAV files

### ISSUE THREAD

**Issue by colugomusic** [mackron/dr_libs#168]
Hello,

am I correct that it is not currently possible to write 24-bit WAV data using this library?

**Comment by colugomusic** [comment]
I think I'm wrong after digging through miniaudio, it appears the relevant data conversion utilities are in there instead, which makes sense. I assumed it would be a part of dr_libs. In this case I want the ma_pcm_*_to_s24 functions.

I assume this will pack the 24-bit values tightly into a byte buffer (instead of doing what some other libraries do where 24-bit values are packed into the last 3 bytes of a 32-bit int). So I will need to allocate a buffer of (3 * num_channels * num_frames) bytes?

**Comment by mackron** [comment]
Yes, that's correct. When you initialize the drwav object make sure you use 24 for the bits per sample, and then write tightly packed 24-bit data with drwav_write_pcm_frames().

**Comment by colugomusic** [comment]
It works beautifully, thanks!
