### ISSUE TITLE
dr_mp3: init_file() uses pFile after previously being freed

### ISSUE THREAD

**Issue by kcgen** [mackron/dr_libs#171]
Hit this after merging the latest dr_mp3:

![2020-12-04_16-31](https://user-images.githubusercontent.com/1557255/101227903-67b20100-364e-11eb-82a1-3eb34bedc37f.png)

The call-stack to get to the initial freeing is this chain here:

![2020-12-04_16-31_1](https://user-images.githubusercontent.com/1557255/101227901-65e83d80-364e-11eb-9132-3b1df1adb6f7.png)

If `pFile` could be initialized with `NULL`, and then always set to NULL on free/close, then you could check for NULL prior to further closing. (just an idea).

**Comment by mackron** [comment]
I left a comment in the pull request - your version is one day out of date.
