### ISSUE TITLE
dr_wav: Always true comparison (flagged by lgtm)

### ISSUE THREAD

**Issue by kcgen** [mackron/dr_libs#174]
![Screenshot_20210119-112038_Brave](https://user-images.githubusercontent.com/1557255/105086077-9133ba00-5a4d-11eb-8f38-f6e180693731.jpg)

**Comment by mackron** [comment]
This should be fixed in the dev branch. Can you check that?

**Comment by kcgen** [comment]
Analysis underway at https://lgtm.com/projects/g/dosbox-staging/dosbox-staging/rev/pr-87ed9c3d37e0a4e1581338db8305a4df6f1253e2

**Comment by kcgen** [comment]
That fixed it, thanks @mackron !

**Comment by mackron** [comment]
Cheers.
