### ISSUE TITLE
dr_mp3: (minor) empty code blocks missing reasons

### ISSUE THREAD

**Issue by kcgen** [mackron/dr_libs#175]
![Screenshot_20210119-112219_Brave](https://user-images.githubusercontent.com/1557255/105086409-d35cfb80-5a4d-11eb-993e-c068d39481ae.jpg)

**Comment by mackron** [comment]
That's from minimp3 which I'm keeping consistent with upstream. Will not fix.

**Comment by kcgen** [comment]
Fixed upstream in minimp3 here: https://github.com/lieff/minimp3/commit/ef9e212fa29bb72d23558da21bb5694fd2d01768

**Comment by mackron** [comment]
Will update dr_mp3 soon. Thanks.

**Comment by mackron** [comment]
Fixed in the dev branch.
