### ISSUE TITLE
dr_flac: comparison is always true (flagged by lgtm)

### ISSUE THREAD

**Issue by kcgen** [mackron/dr_libs#176]
![Screenshot_20210119-112110_Brave](https://user-images.githubusercontent.com/1557255/105086692-3cdd0a00-5a4e-11eb-9a3f-5832d60fa2c8.jpg)

**Comment by mackron** [comment]
Setting this to Will Not Fix. The way this is written is useful for humans when scanning the code because it makes it clearer as to which block will be executed depending on the value of `blockSize`.

**Comment by kcgen** [comment]
Thanks for the explanation @mackron ; will add this to the ignore list with your explanation.

**Comment by kcgen** [comment]
Thanks for the explanation @mackron.
@dreamer, would you be able suppress this warning in LGTM with the explanation above as justification?

**Comment by dreamer** [comment]
@kcgen no, I can't - I can either hide all "comparison always true" warnings (we don't want that), or place a comment in dr_flac header (which means we will need to re-apply patch after updating the library - we don't want that either).

@mackron If the purpose of this check is to document the code, then would you be open to PR that addresses this issue this way?

```C++
    } else if (blockSize <= 5) {
        assert(blockSize >= 2);
```
