### ISSUE TITLE
dr_wav resample?

### ISSUE THREAD

**Issue by wushange** [mackron/dr_libs#191]
Hello, I'm an Android application developer. I'm working on JNI recently. I need to resample the wav file just like the resample method in MATLAB. Now I have no problem generating audio with drwav. I wonder if the example method is available for use.

**Comment by mackron** [comment]
Unfortunately there's no resampling available in dr_wav, nor any other dr_libs library. That's something you'll need to organise yourself. My miniaudio project has a simple linear resampler available that you might be able to extract or use a reference (search for `ma_linear_resampler`): https://github.com/mackron/miniaudio/blob/master/miniaudio.h

Alternatively there's other resampling libraries out there such as [libresample](https://github.com/minorninth/libresample) and [libsamplerate](https://github.com/libsndfile/libsamplerate). I haven't used these before and cannot tell you whether or not they're high quality libraries.

**Comment by wushange** [comment]
Thank you very much for your timely reply. I'm going to use your miniaudio for the experiment.

**Comment by Ghabry** [comment]
I can recommend libspeexdsp. The library gives good results and is much faster than libsamplerate (never used libresample)
