### ISSUE TITLE
dr_flac: 16-bit output?

### ISSUE THREAD

**Issue by deltabeard** [mackron/dr_libs#20]
Hello,

I'm currently using the dr_flac library to play [flac files on the 3DS](https://github.com/deltabeard/ctrmus/tree/flac). The 3DS can only play 16-bit PCM streams, so I tried to make a number of changes to the library to return the samples in 16-bit but it was buggy and I didn't really know what I was doing.

I was wondering if you could recommend any changes that I could make to your library to return samples in 16-bit rather than 32-bit?

Thank you in advance.

**Comment by mackron** [comment]
I've actually had a few people ask for this now so I might just get this done myself... The easiest, but less efficient, way to do this would be to just wrap drflac_read_s16() around _s32() and do a second pass which just right-shifts each 32-bit sample by 16 bits and casts to dr_int16.

I'll take a look at this today and update this issue accordingly.

**Comment by mackron** [comment]
OK, I just pushed an update to dr_flac for 16-bit output. Just use the new _s16() APIs instead of _s32() and you should be good. Note that I've not done any detailed testing - just a quick listening test.

**Comment by deltabeard** [comment]
Tested working on the 3DS. Thank you very much!
