### ISSUE TITLE
Potential security issue

### ISSUE THREAD

**Issue by zidingz** [mackron/dr_libs#203]
Hey there!

I belong to an open source security research community, and a member (@rickdejager) has found an issue, but doesn’t know the best way to disclose it.

If not a hassle, might you kindly add a `SECURITY.md` file with an email, or another contact method? GitHub [recommends](https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository) this best practice to ensure security issues are responsibly disclosed, and it would serve as a simple instruction for security researchers in the future.

Thank you for your consideration, and I look forward to hearing from you!

(cc @huntr-helper)

**Comment by mackron** [comment]
Just email me. Address is at the top of each file.

**Comment by mackron** [comment]
This issue should be fixed. I know I said to email me earlier, but in future please just report the issue here publicly like any other bug report. Also, Docker images are useless to me. All I need is a sample file that triggers the error.

Thanks for the report!
