### ISSUE TITLE
Big Endian: Assert in drwav__bswap_samples_pcm for bytesPerSample = 1

### ISSUE THREAD

**Issue by Ghabry** [mackron/dr_libs#204]
We are hitting an assert when playing any 8 bit sample on a big endian system through the s16 api.

Callstack:

```
__assert_fail 0x00007f8c93934616
drwav__bswap_samples_pcm dr_wav.h:1652
drwav__bswap_samples dr_wav.h:1689
drwav_read_pcm_frames_be dr_wav.h:5217
drwav_read_pcm_frames dr_wav.h:5228
drwav_read_pcm_frames_s16__pcm dr_wav.h:5996
drwav_read_pcm_frames_s16 dr_wav.h:6126
```

The problem is the default handler:

```cpp
    switch (bytesPerSample)
    {
        case 2: /* s16, s12 (loosely packed) */
        {
            drwav__bswap_samples_s16((drwav_int16*)pSamples, sampleCount);
        } break;
        case 3: /* s24 */
        {
            drwav__bswap_samples_s24((drwav_uint8*)pSamples, sampleCount);
        } break;
        case 4: /* s32 */
        {
            drwav__bswap_samples_s32((drwav_int32*)pSamples, sampleCount);
        } break;
        default:
        {
            /* Unsupported format. */
            DRWAV_ASSERT(DRWAV_FALSE);
        } break;
    }
```

guess the fix is to add a "no-op" handler for the 1 byte case because 1 byte does not need byte-swapping. (``drwav__bswap_samples_ieee`` below has the same bug assuming 1 byte float files exist)

**Comment by mackron** [comment]
Thanks for the report, and sorry I took so long to respond. Good catch! I've pushed a fix to the dev branch - are you to check if that fixes the problem?

I've left out the check for the theoretical 1-byte float. That's not something I'm really interested in supporting so I'm happy to let that one fall through to the assert.

Commit: https://github.com/mackron/dr_libs/commit/c8465fc5b41b36f69def8700c35cf25804eb1000

**Comment by Ghabry** [comment]
sorry for the late response. Yes can confirm that it does not crash anymore (and also sound correct).

**Comment by mackron** [comment]
Thanks for confirming that for me. I'll get this released soon.

**Comment by mackron** [comment]
I've finally got this fix released. Thanks for the report!
