### ISSUE TITLE
dr_wav 0.13.2: PVS Studio flagged dead code due to always-true condition

### ISSUE THREAD

**Issue by kcgen** [mackron/dr_libs#206]
![2021-10-02_10-16_1](https://user-images.githubusercontent.com/1557255/135729645-2c1b6a7e-9035-4fe2-8a2d-a82b6d90b82f.png)

(Maybe an assert would cover this case?)

[dr_wav-0.13.2-pvs-issues.tar.gz](https://github.com/mackron/dr_libs/files/7272079/dr_wav-0.13.2-pvs-issues.tar.gz)

**Comment by mackron** [comment]
This check is relevant and valid for 32-bit builds where `cap` may indeed exceed `SIZE_MAX` (albeit extremely unlikely). Setting this one to wontfix.

**Comment by kcgen** [comment]
Thanks for the quick assesment @mackron ; makes sense, and will add an exclussion.
