### ISSUE TITLE
RIFX support

### ISSUE THREAD

**Issue by rasky** [mackron/dr_libs#210]
I found a WAV file that dr_wav couldn't open. Inspecting it showed a `RIFX` header. I found references online that is identical to a standard RIFF file, but with all fields in big endian. I guess this is not currently supported by dr_wav.

It looks like this is generated by sox using the -B / --big-endian option, so it might be less obscure than I thought.

**Comment by mackron** [comment]
I'm happy to support this eventually. Probably won't happen in the short term, however. Will leave this one open as a feature request and get to it at some point. Thanks for the suggestion!

**Comment by mackron** [comment]
I've finally got around the implementing this. It's in the dev branch if you were wanting to give that a try.

Metadata is not supported.

**Comment by rasky** [comment]
Thanks, it works for me!
