### ISSUE TITLE
dr_wav (0.13.3): Coverity flagged Untrusted loop bound (CWE-606)

### ISSUE THREAD

**Issue by kcgen** [mackron/dr_libs#213]
"An attacker could control the number of times the loop iterates. In `drwav__read_cue_to_metadata_obj`: An unscrutinized value from an untrusted source used as a loop bound (CWE-606)"

![2021-11-28_06-37](https://user-images.githubusercontent.com/1557255/143772459-542c8099-71e8-43f2-bdde-094308d034ae.png)

**Comment by kcgen** [comment]
@mackron , we have a handful of Coverity scans per week, so unfortunately I wasn't able to get these results to you earlier. It runs after pushing to the `main` branch, and these came in last night after I updated to dr_wav 0.13.3 in the project.

**Comment by mackron** [comment]
Thanks. I'll get this cleaned up soon.

**Comment by mackron** [comment]
All of these latest issues should be fixed in the dev branch. Are you able to give that another run when you get a chance?

**Comment by kcgen** [comment]
Scan finished up for `0.13.4-dev` 

Five issues down!

![2021-12-07_09-51](https://user-images.githubusercontent.com/1557255/145080759-496b3df1-2082-4c0c-9a26-dd2300b91266.png)

**Comment by kcgen** [comment]
Only three remain (in total) in the dr_libs:

![2021-12-07_10-05](https://user-images.githubusercontent.com/1557255/145082883-30f533c9-4028-4797-8377-5b93607fd856.png)

It seems these are a bit older than 0.13.3, so my fault for not posting them earlier! They seem to be of a similar nature as this current round.

**Comment by mackron** [comment]
Thanks. These fixes have been released.
