### ISSUE TITLE
dr_wav (0.13.3): Coverity flagged Untrusted loop bound (CWE-606)

### ISSUE THREAD

**Issue by kcgen** [mackron/dr_libs#214]
"An attacker could control the number of times the loop iterates. In drwav__read_smpl_to_metadata_obj: An unscrutinized value from an untrusted source used as a loop bound."

![2021-11-28_06-42](https://user-images.githubusercontent.com/1557255/143772675-05e9ca11-ea34-4a05-99be-b13a6d5a3138.png)

**Comment by mackron** [comment]
Should be fixed in the dev branch. See https://github.com/mackron/dr_libs/issues/213 for discussion.

**Comment by kcgen** [comment]
Confirmed fixed!
