### ISSUE TITLE
dr_wav (dev): Coverity flagged Untrusted loop bound (CWE-606) in `drwav_init__internal`

### ISSUE THREAD

**Issue by kcgen** [mackron/dr_libs#218]
_"An attacker could control the number of times the loop iterates. In `drwav_init__internal`, an unscrutinized value from an untrusted source used as a loop bound (CWE-606)"_

![2021-12-07_10-03](https://user-images.githubusercontent.com/1557255/145083816-29c2ee64-f74b-4f14-bfd9-964bd77d4b29.png)
![2021-12-07_10-03_1](https://user-images.githubusercontent.com/1557255/145083813-a2d13fbb-538a-41d6-90f4-c11935df41e4.png)
![2021-12-07_10-04](https://user-images.githubusercontent.com/1557255/145083812-35a197f4-93bf-45bf-aba0-23e78fd2ea2b.png)
![2021-12-07_10-04_1](https://user-images.githubusercontent.com/1557255/145083809-d2a0eeec-f2ca-424f-be38-94c6db0f8149.png)

**Comment by mackron** [comment]
Same as https://github.com/mackron/dr_libs/issues/219. Nothing to fix here because a chunk size can be anything and there's nothing practical to use as a bound check. If the data is invalid, seeking will fail. Setting to wontfix.

**Comment by kcgen** [comment]
Thanks for the explanation @mackron.

My guess is it wanted a logical bound: a simple example might be that the chunk-size (should) never exceed the WAV file size.  None the less, if the seek routine will catch it - then might as well pass it through to try.  

I've marked it as a false-positive and won'tfix - thanks for the quick assessment @mackron !
