### ISSUE TITLE
dr_wav (dev): Coverity flagged Untrusted loop bound (CWE-606) in `drwav__read_fmt`

### ISSUE THREAD

**Issue by kcgen** [mackron/dr_libs#219]
_"An attacker could control the number of times the loop iterates. In `drwav__read_fmt`, an unscrutinized value from an untrusted source used as a loop bound (CWE-606)"_

![2021-12-07_10-02_1](https://user-images.githubusercontent.com/1557255/145084114-e9d8d929-3f8a-44c5-810e-0b86ec29a29c.png)

**Comment by mackron** [comment]
There's nothing to fix here. If the header's size is invalid (i.e. random junk), the seek forward will fail due to it overflowing the size of the file. There's nothing practical to use as a bound check here because a chunk can be any size. Setting this one to wontfix.

**Comment by kcgen** [comment]
Thanks for the explanation. I've marked it as a false-positive and won'tfix - thanks for the quick assessment @mackron !
