### ISSUE TITLE
dr_flac bitstream, unalignedByteCount not cleared

### ISSUE THREAD

**Issue by DrMcCoy** [mackron/dr_libs#22]
Hej!

I'm currently writing a single-file unrar library (GPLv2+-licensed, though, because I'm also basing it on GPLv2+ and LGPLv2.1+ unrar code), and I'm reusing your bitstream code. Thanks for writing it, btw, it's really nice and clean!

I've noticed that `drflac__reload_cache()`, in the [slow path](https://github.com/mackron/dr_libs/blob/master/dr_flac.h#L951), doesn't clear `unalignedByteCount` after loading `unalignedCache` into the L1 cache. Is there a reason for that, or is that a mistake?

Specifically, I *think* there should be a
`bs->unalignedByteCount = 0;`
before the return here: https://github.com/mackron/dr_libs/blob/master/dr_flac.h#L961

Otherwise, when reading past the end of the client buffer, the last n bits will be repeated over and over, instead of the _read* functions returning DR_FALSE. Or am I just missing something?

Cheers,
Sven

**Comment by DrMcCoy** [comment]
Another thing: `drflac__seek_bits()` doesn't seem to take the `unalignedByteCount` into account either.

I.e. when we're at the end of the input buffer and there's unaligned bytes, and seeking goes over the L1 cache, it doesn't check for `unalignedByteCount` before going straigt to `onSeek()`. But when `unalignedByteCount > 0`, we know we're at the end of the data, so we can't seek the client either.

Modifying the line https://github.com/mackron/dr_libs/blob/master/dr_flac.h#L1004 from
```
if (wholeBytesRemaining > 0) {
```
to
```
if (wholeBytesRemaining > 0 && bs->unalignedByteCount == 0) {
```

should do it, I think. The reload when `bitsToSeek > 0` will then reload `cache` from the `unalignedCache`, and the recursive call to drflac__seek_bits() will consume the rest of the bits to seek.

**Comment by mackron** [comment]
Sorry I didn't respond sooner.

It's been a while since I implemented the bit streaming stuff so it's not fresh in my mind right now. I'll need to study this and run some tests to make sure I don't introduce any subtle bugs. I've been meaning to commit some time to my open source work, so I might do it this weekend.

That's an interesting use case for the bit streaming stuff - I'm curious to see how that works out! Is it actually working yet? What's the performance been like for you?

**Comment by DrMcCoy** [comment]
> I'll need to study this and run some tests to make sure I don't introduce any subtle bugs

It seems to work for me, but I might have overlooked something as well. Please keep me updated if you do find issues with this. :)

> Is it actually working yet?

It is, and it works great. I'm still missing a few RAR features I want to implement, but decompression itself works. I'll probably make it public in the next few days, barring any complications.

One thing I had to do was add a peek() function, because I need that for the Huffman decoder (lookup table approach). It's basically a modified `drflac__read_uint32()`, but refilling the L2 cache if necessary, without calling `drflac__reload_cache()` (I moved parts of `drflac__reload_l1_cache_from_l2()` into its own function), so it won't throw away data.

> What's the performance been like for you?

Certainly faster than my own naive bitstreamer. And also still faster than my less naive second approach. :P

unrar-ing as a whole is faster than [The Unarchiver](http://unarchiver.c3.cx/unarchiver) (which is one of the projects I'm basing my unrar code on). Depending on the compression methods, it's about on par to a bit a slower than the original unrar. All in the same ballpark, so I'm quite happy with it.

**Comment by mackron** [comment]
So I took a look at this and I can see the logic in the changes you suggested, and it all seems to work fine. Thanks a lot for this!
