### ISSUE TITLE
dr_wav (dev): Coverity flagged and Untrusted array index read (CWE-129) in `drwav_read_pcm_frames_s16__ima`

### ISSUE THREAD

**Issue by kcgen** [mackron/dr_libs#220]
_"The array index could be controlled by an attacker, leading to reads outside the bounds of the array. In `drwav_read_pcm_frames_s16__ima`: read from array at index computed using an unscrutinized value from an untrusted source (CWE-129)"_

![2021-12-07_10-01](https://user-images.githubusercontent.com/1557255/145084377-f1c47300-54bc-44b0-bd4f-a9502ea938b0.png)
![2021-12-07_10-02](https://user-images.githubusercontent.com/1557255/145084374-1b1fdb0f-6521-4ce6-a078-986bb9118b64.png)

**Comment by mackron** [comment]
There's no bug here because those values are checked in the section right above it. Regardless, I've added a clamp which should clean this error up.

**Comment by kcgen** [comment]
Confirmed fixed; all clean!
Thanks again @mackron 🚀

**Comment by mackron** [comment]
Thanks for confirming that. This fix has been released.
