### ISSUE TITLE
AIFF Decoder

### ISSUE THREAD

**Issue by paulreimer** [mackron/dr_libs#222]
`miniaudio` is such a well-designed & implemented audio lib -- it has almost everything I can imagine using for my project(s).

One additional thing that would make it perfect for my use-case (a new piece of DJ software) would be AIFF file support.

I'm not sure if `dr_libs` would be a better repo to contain this issue, or if an external library approach for AIFF decoding would be the better way to go (similar to `*.ogg` support via stb_vorbis). As well, I'm not up-to-date on any licensing issues that might prevent adding support for AIFF/AIFC files.

I might be able to make an attempt at adding support for this (with some guidance 🤞 on how/where to start, and quite a bit of time learning, to reach the quality level of these repos).

**Comment by mackron** [comment]
Transferred this one over to dr_libs.

**Comment by mackron** [comment]
I've gone ahead and added support for decoding AIFF/AIFC files to dr_wav. It will be amalgamated into miniaudio very soon. Note that it only supports decoding of audio data. It does not support parsing of metadata, nor does it support writing.

This is in the dr_libs dev branch.

**Comment by mackron** [comment]
This has now been amalgamated into miniaudio's dev branch. I'll go ahead and close this one now.
