### ISSUE TITLE
dr_mp3 frameInfo never filled

### ISSUE THREAD

**Issue by MrArnal** [mackron/dr_libs#238]
The member frameInfo of the struct drmp3 is never filled (nor used). It's a nice to have to do realtime display of the frame bitrate in players.

**Comment by mackron** [comment]
Thanks for the report, and sorry for the delay in my response. Unfortunately you're not going to like my answer to this one - I'm just going to be removing that unused member. I'm just not interested in supporting that particular use case. If you want frame-by-frame information, it may actually be better to use the low level API, or just use minimp3 directly (dr_mp3 is a wrapper around minimp3).

**Comment by MrArnal** [comment]
Thx! No worries :)
