### ISSUE TITLE
test dr_wav_playback hardcodes miniaudio include path, intended?

### ISSUE THREAD

**Issue by antecrescent** [mackron/dr_libs#257]
The assumed directory structure:
```
.
├── dr_libs
    ├── tests
        ├── wav
            ├── dr_wav_playback.c
├── miniaudio
    ├── miniaudio.h
```
Is that intended? I propose including a system header instead and updating the `README` accordingly.

**Comment by mackron** [comment]
Yes, that's intentional. The test is for me and nobody else. There's no possibility of me making that a system header.
