### ISSUE TITLE
Suggestion for a MIDI synthesis library

### ISSUE THREAD

**Issue by peteroupc** [mackron/dr_libs#261]
To improve support for MIDI (Musical Instrument Digital Interface) music playback in open-source and other applications, there could be a `dr_*` library for software synthesis of MIDI data stored in standard MIDI files.

Since the other `dr_*` libraries are public-domain, this repository is an ideal venue for a public-domain MIDI solution.  For further details on my request, see:

https://peteroupc.github.io/music.html

This can be seen as a followup to: https://github.com/mackron/miniaudio/issues/158.

**Comment by dromer** [comment]
I'd say this is vastly out of scope for the `dr_libs` project.
Its primary function is for audio decoding.

Adding synthesis techniques (and specifically ones based on MIDI input) is somewhat the opposite of what is intended.
This library being minimal in scope and capability is imo one of its strengths.

Now should a library like you suggest exist? -> absolutely!
Should dr_libs be that library? no.

**Comment by peteroupc** [comment]
Thank you for your response.   Thus this issue is closed, unfortunately.

**Comment by dromer** [comment]
@peteroupc well that's just my personal opinion and interpretation of the project.

Of course @mackron could think differently, but I kind of doubt it.

**Comment by mackron** [comment]
I've had a few people ask for midi across both my dr_libs and miniaudio projects. dr_libs is not the place for it, though I do think a midi library would be valuable.

But unfortunately these days all of my open source work is centred around what I need personally and I just haven't got a need for midi so it's highly unlikely I'll be the one doing a library for that.
