### ISSUE TITLE
dr_flac.h build failure with -fPIC

### ISSUE THREAD

**Issue by sezero** [mackron/dr_libs#35]
This is on CentOS 6.10 / i686 with gcc-4.4.7 as came with the OS:

```
$ gcc -xc -O3 -DDR_FLAC_IMPLEMENTATION -DNDEBUG -std=gnu99 -fPIC -o dr_flac.c.o -c dr_flac.h
dr_flac.h:799:1: warning: "_BSD_SOURCE" redefined
In file included from /usr/include/stdint.h:26,
                 from dr_flac.h:133:
/usr/include/features.h:182:1: warning: this is the location of the previous definition
dr_flac.h: In function ‘drflac__swap_endian_uint16’:
dr_flac.h:921: warning: implicit declaration of function ‘__builtin_bswap16’
dr_flac.h: In function ‘drflac_open_with_metadata_private’:
dr_flac.h:785: error: can't find a register in class ‘BREG’ while reloading ‘asm’
dr_flac.h:785: error: can't find a register in class ‘BREG’ while reloading ‘asm’
dr_flac.h:785: error: ‘asm’ operand has impossible constraints
dr_flac.h:785: error: ‘asm’ operand has impossible constraints
```

The cpuid asm failure seems to be because ebx is the PIC register:
The failure doesn't happen without -fPIC.

The __builtin_bswap16 warning is there because, unlike __builtin_bswap32,
__builtin_bswap16 is added in gcc-4.8, not gcc-4.3.

gcc-4.9.4 fails in a similar way:
```
$ gcc49 -xc -O3 -DDR_FLAC_IMPLEMENTATION -DNDEBUG -std=gnu99 -fPIC -o dr_flac.c.o -c dr_flac.h
dr_flac.h:799:0: warning: "_BSD_SOURCE" redefined
 #define _BSD_SOURCE
 ^
In file included from /usr/include/stdint.h:26:0,
                 from /opt/gcc490/lib/gcc/i686-pc-linux-gnu/4.9.4/include/stdint.h:9,
                 from dr_flac.h:133:
/usr/include/features.h:182:0: note: this is the location of the previous definition
 # define _BSD_SOURCE 1
 ^
dr_flac.h: In function 'drflac_open_with_metadata_private':
dr_flac.h:785:17: error: inconsistent operand constraints in an 'asm'
                 __asm__ __volatile__ (
                 ^
dr_flac.h:785:17: error: inconsistent operand constraints in an 'asm'
                 __asm__ __volatile__ (
                 ^
```

**Comment by mackron** [comment]
That's annoying. I expect a few of my other libraries have the same problem... Will take a look at this when I get a chance.

Thanks for the report!

**Comment by mackron** [comment]
I've done a potential fix for this in the "dev_flac" branch. Could you try that out and let me know how you go? I've not tried compiling with gcc-4.9.

**Comment by sezero** [comment]
It builds for me.  I was about to send a PR to you, you beat me to it :)

For the __builtin_swap16 issue, we practically did the same thing.

If you are interested:
for _BSD_SOURCE define, I did the following instead:
```
diff --git a/dr_flac.h b/dr_flac.h
index c836847..ffadb5a 100644
--- a/dr_flac.h
+++ b/dr_flac.h
@@ -796,7 +808,9 @@ const char* drflac_next_vorbis_comment(drflac_vorbis_comment_iterator* pIter, dr
 
 
 #ifdef __linux__
+#ifndef _BSD_SOURCE
 #define _BSD_SOURCE
+#endif
 #include <endian.h>
 #endif
 ```

And, for cpuid and -fPIC, I did the following instead (following gcc's own cpuid.h):
```
diff --git a/dr_flac.h b/dr_flac.h
index c836847..ffadb5a 100644
--- a/dr_flac.h
+++ b/dr_flac.h
@@ -780,12 +780,24 @@ const char* drflac_next_vorbis_comment(drflac_vorbis_comment_iterator* pIter, dr
         #endif
     #else
         #if defined(__GNUC__) || defined(__clang__)
+            #ifndef __PIC__
             static void drflac__cpuid(int info[4], int fid)
             {
                 __asm__ __volatile__ (
                     "cpuid" : "=a"(info[0]), "=b"(info[1]), "=c"(info[2]), "=d"(info[3]) : "a"(fid), "c"(0)
                 );
             }
+            #else
+            static void drflac__cpuid(int info[4], int fid)
+            {
+                __asm__ __volatile__ (
+                    "xchg{l}\t{%%}ebx, %k1\n\t"
+                    "cpuid\n\t"
+                    "xchg{l}\t{%%}ebx, %k1\n\t"
+                      : "=a"(info[0]), "=&r"(info[1]), "=c"(info[2]), "=d"(info[3]) : "a"(fid), "c"(0)
+                );
+            }
+            #endif
         #else
         #define DRFLAC_NO_CPUID
         #endif
```

**Comment by sezero** [comment]
Noticed one issue with __builtin_bswap16 fix:
Now that `__GNUC__` check is done without any accompanying version
checks on the same line, `__clang__` check must come before it.  i.e:

```
diff --git a/dr_flac.h b/dr_flac.h
index 2f60c1f..850aa60 100644
--- a/dr_flac.h
+++ b/dr_flac.h
@@ -825,14 +825,6 @@ const char* drflac_next_vorbis_comment(drflac_vorbis_comment_iterator* pIter, dr
     #define DRFLAC_HAS_BYTESWAP16_INTRINSIC
     #define DRFLAC_HAS_BYTESWAP32_INTRINSIC
     #define DRFLAC_HAS_BYTESWAP64_INTRINSIC
-#elif defined(__GNUC__)
-    #if ((__GNUC__ > 4) || (__GNUC__ == 4 && __GNUC_MINOR__ >= 3))
-        #define DRFLAC_HAS_BYTESWAP32_INTRINSIC
-        #define DRFLAC_HAS_BYTESWAP64_INTRINSIC
-    #endif
-    #if ((__GNUC__ > 4) || (__GNUC__ == 4 && __GNUC_MINOR__ >= 8))
-        #define DRFLAC_HAS_BYTESWAP16_INTRINSIC
-    #endif
 #elif defined(__clang__)
     #if __has_builtin(__builtin_bswap16)
         #define DRFLAC_HAS_BYTESWAP16_INTRINSIC
@@ -843,6 +835,14 @@ const char* drflac_next_vorbis_comment(drflac_vorbis_comment_iterator* pIter, dr
     #if __has_builtin(__builtin_bswap64)
         #define DRFLAC_HAS_BYTESWAP64_INTRINSIC
     #endif
+#elif defined(__GNUC__)
+    #if ((__GNUC__ > 4) || (__GNUC__ == 4 && __GNUC_MINOR__ >= 3))
+        #define DRFLAC_HAS_BYTESWAP32_INTRINSIC
+        #define DRFLAC_HAS_BYTESWAP64_INTRINSIC
+    #endif
+    #if ((__GNUC__ > 4) || (__GNUC__ == 4 && __GNUC_MINOR__ >= 8))
+        #define DRFLAC_HAS_BYTESWAP16_INTRINSIC
+    #endif
 #endif
 
 
```

**Comment by mackron** [comment]
Yeah I also did that with _BSD_SOURCE, but then I questioned why I was even including <endian.h> in the first place. Removing it didn't break anything for me so I just figured I'd remove it entirely.

The saving and restoring of the ebx register actually looks cleaner in your version. I might even copy that.

Does Clang define __GNUC__? (It defines _MSC_VER and it's really annoying!)

**Comment by sezero** [comment]
> Yeah I also did that with _BSD_SOURCE, but then I questioned why I was even
> including <endian.h> in the first place. Removing it didn't break anything for me
> so I just figured I'd remove it entirely.

endian.h is needed for be16toh() which is guarded by `__USE_BSD` which is
only enabled if `_BSD_SOURCE` is defined.  I think the build succeeds for me
only because I use `-std=gnu99` on the command line.

> The saving and restoring of the ebx register actually looks cleaner in your version.
> I might even copy that.

Feel free to do so!

> Does Clang define `__GNUC__`?

Yep.  I advertises itself as gcc-4.2.1 for compatibility:
```
$ clang -E -dD -xc /dev/null|grep __GNUC
#define __GNUC_MINOR__ 2
#define __GNUC_PATCHLEVEL__ 1
#define __GNUC__ 4
#define __GNUC_STDC_INLINE__ 1
```

**Comment by mackron** [comment]
Yeah I just looked at the man pages for `be16toh()` et al. and indeed it has...

```
#define _BSD_SOURCE             /* See feature_test_macros(7) */
#include <endian.h>
```

... so I went ahead and put that back in (pushed to `dev_flac`). I also updated the Clang ordering thing in case you missed the edit I made to my earlier comment.

**Comment by sezero** [comment]
Thanks.

**Comment by sezero** [comment]
Here is a better solution for be16toh() and `_BSD_SOURCE`, which bulids
not only -with `-std=gnu99` but also with `-std=c99` :

```
diff --git a/dr_flac.h b/dr_flac.h
index 73cdc94..d0cb5a4 100644
--- a/dr_flac.h
+++ b/dr_flac.h
@@ -118,6 +118,10 @@
 #ifndef dr_flac_h
 #define dr_flac_h
 
+#if defined(__linux__) && !defined(_BSD_SOURCE)
+#define _BSD_SOURCE     /* for be16toh() & co. */
+#endif
+
 #include <stddef.h>
 
 #if defined(_MSC_VER) && _MSC_VER < 1600
@@ -805,9 +809,6 @@ const char* drflac_next_vorbis_comment(drflac_vorbis_comment_iterator* pIter, dr
 
 
 #ifdef __linux__
-#ifndef _BSD_SOURCE
-#define _BSD_SOURCE
-#endif
 #include <endian.h>
 #endif
 
```

**Comment by mackron** [comment]
The only thing I don't like about that solution is how the `#define` is now in the header section instead of the implementation section. As a general rule I like to avoid putting things like that in the header section - having it in the implementation section just keeps it more isolated. I have pushed an alternate solution that I _think_ would work (I tested with gnu99 and c99). See commit 1e9ddef133b311bb844e0d2f2932f8e3c75b5efe.

**Comment by sezero** [comment]
That works, thanks.

**Comment by sezero** [comment]
What else is left to close this?  (Will you replace the cpuid() stuff for i386-PIC case?)

**Comment by mackron** [comment]
Yeah I was just researching that inlined assembly stuff. I've just pushed an update which uses a similar technique to the one you mentioned earlier except that it uses `%k0` instead of `%k1` for the temporary register. Will that make any difference, do you know?

**Comment by sezero** [comment]
My asm (and gcc's inline asm) knowledge is less than little, but IIRC, %<num> means
operand number: %0 means the first, %1 means the second.  We are using "=&r" for
the second operand to leave register choice to gcc, so I _think_ %1 is needed there to
save ebx to that whatever register.  The diff between k0 and k1 is like the following,
k0 seems wrong:
```
--- k0
+++ k1
@@ -11,9 +11,9 @@
 	movl	12(%ebp), %eax
 	movl	%edi, 4(%esp)
 	movl	8(%ebp), %esi
-	xchgl %ebx, %eax
+	xchgl %ebx, %edi
 	cpuid
-	xchgl %ebx, %eax
+	xchgl %ebx, %edi
 	movl	%eax, (%esi)
 	movl	%edi, 4(%esi)
 	movl	%ecx, 8(%esi)
```

**Comment by mackron** [comment]
Ah yeah, of course. You're right. Fixed (I think).

**Comment by sezero** [comment]
Seems OK now, thanks.

BTW, using a newline ('\n\t') instead of semicolon (';') gives a more
readable output witth gcc -S, but that's your choice of coding style.

**Comment by mackron** [comment]
Yeah I was aware of that actually, but I just favour a cleaner look in the C code.

I have merged these changes into the master branch. Thanks for your help with all that!

**Comment by sezero** [comment]
You're welcome.
