### ISSUE TITLE
Small typo in comment

### ISSUE THREAD

**Issue by ypujante** [mackron/dr_libs#43]
I know it's just in the comment/usage documentation but if you simply copy/paste it does not compile:

https://github.com/mackron/dr_libs/blob/master/dr_wav.h#L43

```
// does not compile
//     float* pSampleData = drwav_open_and_read_file_s32("my_song.wav", &channels, &sampleRate, &totalSampleCount);

// should be =>
//     float* pSampleData = drwav_open_and_read_file_f32("my_song.wav", &channels, &sampleRate, &totalSampleCount);
```

**Comment by mackron** [comment]
I've fixed this in the dev_wav branch which I'll merge into master in a future release of dr_wav. Thanks for the report!
