### ISSUE TITLE
Strange sounding wav decoding?

### ISSUE THREAD

**Issue by fungos** [mackron/dr_libs#44]
I'm really not sure where the problem is with some wave files I'm testing, check this one for instance:

https://mega.nz/#!FEEFDYIL!pTcZgyRD_0Y0XR3YypsxG6fqo-zt5ZLwnCEw8Dwbfks

You can play this file over VLC as the ground truth, as there it sound perfectly (or, for my use case - exactly the same as BASS plays it).

I ported the audio system from an open source game re-implementation from BASS to SoLoud (that uses dr_wav internally) and a lot of waves sounded weirdly.
To validate it wasn't anything I did wrong, I extracted this wav and played through different players, including the mini_al play sample. 
This showed me that dr_wav may have a relation to the issue, as both mini_al and soloud plays it wrongly. I tested all soloud backends (it does not use mini_al) and all mini_al backends on windows and every backend sounded the same too.

Thanks

**Comment by mackron** [comment]
Thanks for this - I'll look at it as soon as I get a chance.

**Comment by mackron** [comment]
Potential fix is in the "wav/dev" branch. Can you take a look at that and let me know how you go?

**Comment by fungos** [comment]
Yeah, that fix works perfectly with all sounds I tested here. Thanks a lot!
