### ISSUE TITLE
compile warning

### ISSUE THREAD

**Issue by rpvelloso** [mackron/dr_libs#46]
https://github.com/mackron/dr_libs/blob/master/dr_mp3.h#L3035

dr_mp3.h:3035:18: warning: 'priorSeekPointIndex' may be used uninitialized in this function [-Wmaybe-uninitialized] drmp3_uint32 priorSeekPointIndex;

**Comment by mackron** [comment]
Thanks for the report. I have pushed a potential fix for this in the "mp3/dev" branch. Are you able to quickly verify that it's fixed?

**Comment by rpvelloso** [comment]
fixed. Thanks!
