### ISSUE TITLE
dr_mp3 missing prototype definition for drmp3_get_mp3_and_pcm_frame_count(...)

### ISSUE THREAD

**Issue by krcroft** [mackron/dr_libs#50]
Super minor, but a handy function I use. 

Before: 
`error: ‘drmp3_get_mp3_and_pcm_frame_count’ was not declared in this scope`

Compiles clean after adding the prototype: 
`drmp3_bool32 drmp3_get_mp3_and_pcm_frame_count(drmp3* pMP3, drmp3_uint64* pMP3FrameCount, drmp3_uint64* pPCMFrameCount);`

**Comment by mackron** [comment]
Do you mean putting this in the public header section? Can't see why I couldn't do that...

**Comment by mackron** [comment]
I've gone ahead and pushed this to the mp3/dev branch. Could you give that a try? Thanks!

**Comment by krcroft** [comment]
Another one down.. 
Confirming the update compiles without warning on gcc and mingw 1.0 and runs clean, thank you Dave!

**Comment by mackron** [comment]
Thanks for trying that out. Just working on a few more dr_mp3 jobs before merging this into master, but it'll be done soon.

**Comment by krcroft** [comment]
Perfect; will pull down master when it's ready.  All is working well from dev/mp3 in the meantime.

**Comment by mackron** [comment]
It's in master now.
