### ISSUE TITLE
dr_flac: drflac__crc32_table global causes unused variable warning when DR_FLAC_NO_CRC not defined

### ISSUE THREAD

**Issue by krcroft** [mackron/dr_libs#51]
Super minor - 

The static global `drflac__crc32_table` should be wrapped in:
```
#ifndef DR_FLAC_NO_CRC
#endif 
```
Similar to the existing #ifdef around the line of code that uses it inside the  `drflac_crc32_byte(...)` function.

Otherwise it causes a gcc unused variable warning with -Wall -pedantic

**Comment by mackron** [comment]
Good catch. I've pushed a potential fix to the flac/dev branch. Could you verify that real quick before I merge into master?

Thanks for the report!

**Comment by krcroft** [comment]
Confirming the update compiles without warning on gcc and mingw 1.0 and runs clean, thank you Dave!
