### ISSUE TITLE
Push API for dr_wav/dr_flac?

### ISSUE THREAD

**Issue by jprjr** [mackron/dr_libs#52]
Hi there - I noticed dr_mp3 has a push-style API, as does stb_vorbis.

I didn't know if there were any plans to implement one - or is there a way to do it with the decoders as-is?

I've got an application where I just read audio data as it comes in, via pipe, and decode whatever I have available. Right now it just accepts raw PCM samples, I was hoping to add the ability to decode other codecs in a similar way.

Thank you in advance, these are such great libraries!

**Comment by mackron** [comment]
You can still do this with a pull style API, only it's a little more difficult. You would need to implement the read and seek callbacks and pass them to drflac_open(). I have no plans to add a push style API to either dr_flac nor dr_wav.
