### ISSUE TITLE
dr_mp3.h the 2168 line

### ISSUE THREAD

**Issue by gitHubDingDingYu** [mackron/dr_libs#53]
static const drmp3_f4 g_scale = { 32768.0f, 32768.0f, 32768.0f, 32768.0f };
My Android Studio report that: Excess elements in scalar initializer
How can I deal with it?

**Comment by mackron** [comment]
A possible solution may be to replace this code
```
static const drmp3_f4 g_scale = { 32768.0f, 32768.0f, 32768.0f, 32768.0f };
drmp3_f4 a = DRMP3_VMUL(DRMP3_VLD(&in[i  ]), g_scale);
drmp3_f4 b = DRMP3_VMUL(DRMP3_VLD(&in[i+4]), g_scale);
```
with this code
```
drmp3_f4 scale = DRMP3_VSET(32768.0f);
drmp3_f4 a = DRMP3_VMUL(DRMP3_VLD(&in[i  ]), scale);
drmp3_f4 b = DRMP3_VMUL(DRMP3_VLD(&in[i+4]), scale);
```
However, this code is actually from minimp3 (which dr_mp3 wraps around) so the author of minimp3 may have some better insight (and may want to also want fix this there as well). @lieff do you think this solution is suitable? (Here's the line in minimp3: https://github.com/lieff/minimp3/blob/fb1b696969b6a8e6f9ef70ab4f5d28f0f2113ae3/minimp3.h#L1788)

**Comment by lieff** [comment]
Yes, this is suitable solution. Just checked: all recent compilers gcc/clang/msvc successfully optimizes DRMP3_VSET(32768.0f); into const reference same as g_scale variant.

**Comment by lieff** [comment]
But this is strange that it fails. I assume Android Studio default compiler is clang and I've checked arm/arm64/x86/x64 and it takes g_scale variant just fine. What architecture is failing? And what it Android NDK version?

**Comment by gitHubDingDingYu** [comment]
Compiler is clang. Ndk version 19.2.5345600 @lieff

**Comment by mackron** [comment]
I've gone ahead and pushed a fix to the dev branch. Could you try that out and let me know how it goes?

**Comment by mackron** [comment]
I've gone ahead and released this fix. If you find more compilation errors feel free to open a new issue.

**Comment by lieff** [comment]
I think we need to understand what`s going wrong first. Also strange that line { 32768.0f, 32768.0f, 32768.0f, 32768.0f } goes after static const drmp3_f4 g_max = { 32767.0f, 32767.0f, 32767.0f, 32767.0f }; is there error too or not?

I've tried to compile modified hello jni example with NDK 20 and it compiles fine. Something wired happen and it's good to understand this underwater rock.

@gitHubDingDingYu Can you also check modified hello jni android example?

**Comment by mackron** [comment]
I also modified that line in my commit. Here's my commit in case you're curious: 47e346e8497c5a1efbe48b9bd53b19f09f57eb0f

I wasn't able to reproduce it personally so I've got no idea what configuration would be triggering this.

**Comment by mackron** [comment]
Not heard anything back from the original poster so closing this issue now. If this shows up again I'm happy to take a further look.
