### ISSUE TITLE
dr_flac: Rename drflac_cpuid to drflac__cpuid

### ISSUE THREAD

**Issue by MikuAuahDark** [mackron/dr_libs#54]
It causes build failure in MSVC 2013 x86. https://bitbucket.org/rude/love/commits/d1b3742767b0acdb6aff1cb20a0813211ab580c5

**Comment by mackron** [comment]
What's the error? Seems awfully strange that and identifier called "drflac_cpuid" would cause a compiler error...

**Comment by MikuAuahDark** [comment]
It seems `drflac_cpuid` is undefined in MSVC 2013 x86, but `drflac__cpuid`
is (notice the double underscore).

You can see in
https://ci.appveyor.com/project/AlexSzpakowski/love/builds/25542242 the
build fails because `drflac_cpuid` is undefined.

Pada tanggal Rab, 26 Jun 2019 15.48, David Reid <notifications@github.com>
menulis:

**Comment by mackron** [comment]
Ah, I see. Good catch, and thanks for the report! I've fixed this and bumped the version.
