### ISSUE TITLE
[dr_wav] Connection to openal

### ISSUE THREAD

**Issue by ScrappyCocco** [mackron/dr_libs#57]
Have you ever used openal?
Because i have a problem, using [openal-soft](https://github.com/kcat/openal-soft)
A mono .wav sound is loaded correctly and is correctly 3d spatialized
A stereo (double channel) .wav sound is played only from one speaker (the one on the right in my case).
It looks like is played from both speakers when using headphones but is very very low on the left one.
Edit: after trying several headphones i can confirm it only play on the right channel
I don't understand if i'm missing something while loading the .wav using dr_wav to openal buffer or if i did something wrong using openal

PS: Stereo sounds should not be spatialized by openal and should be played as 2d sounds by openal, so from both speakers, the sound/listener position is not a problem here

**Comment by mackron** [comment]
dr_wav is independent of any audio playback library so I'm doubtful it's anything to do with dr_wav. Certainly it works fine with miniaudio as I use them both extensively with each other.

It's certainly a strange symptom, though. Are you doing any data conversion between reading from dr_wav and loading into the OpenAL buffer? Also, I expect you've already tried this, but make double sure your sound source and your listener are positioned at the origin when testing.

**Comment by ScrappyCocco** [comment]
Of course is not dr_wav fault, i was saying it might be my fault about how i use it
What kind of data conversion i might be doing? I just read the data and put it in the buffer
The lenght is correct, i'm just thinking if openal want a specific data-format for double channel audio

**Comment by mackron** [comment]
It depends what your OpenAL buffer's format is set to. AL_FORMAT_STEREO16 will be the same format as the data returned by drwav_read_pcm_frames_s16(). What function are you using to read from dr_wav, and what is the format of your OpenAL buffer?

**Comment by ScrappyCocco** [comment]
I can confirm my format is set to AL_FORMAT_STEREO16 

I'm reading just like the example, like that
```cpp
//Set the sample rate
const ALsizei freq = static_cast<ALsizei>(p_wav_->sampleRate);

//Allocate and read content of file
const size_t memory_size = static_cast<size_t>(p_wav_->totalPCMFrameCount) * p_wav_->channels * sizeof(int32_t);
int32_t* p_sample_data = static_cast<int32_t*>(malloc(memory_size));
drwav_read_s32(p_wav_, p_wav_->totalPCMFrameCount * p_wav_->channels, p_sample_data);

//Convert size
const ALsizei buffer_size = static_cast<ALsizei>(memory_size);

//Fill buffer
alBufferData(buffer_, format, p_sample_data, buffer_size, freq);
```

So am i doing it wrong because i should use `drwav_read_pcm_frames_s16()` ?

**Comment by mackron** [comment]
Yep, that'll be it. The "16" in AL_FORMAT_STEREO16 means signed 16-bit integer. You need to make two changes:

Change your memory allocation size to this (note the change from `sizeof(int32_t)` to `sizeof(int16_t)`).
```
const size_t memory_size = static_cast<size_t>(p_wav_->totalPCMFrameCount) * p_wav_->channels * sizeof(int16_t);
```
And use the following to read from dr_wav:
```
drwav_read_pcm_frames_s16(p_wav_, p_wav_->totalPCMFrameCount, p_sample_data);
```

**Comment by ScrappyCocco** [comment]
Oh yeah i should have known that, sorry, just the last questions

* Why `drwav_read_pcm_frames_s16` and not `drwav_read_s16` ? What's the difference?

* What if the format is `AL_FORMAT_STEREO8`? Doesn't seems to be a function for 8-bit

**Comment by mackron** [comment]
`drwav_read_s16()` has been deprecated and will be removed very soon. `drwav_read_s16()` operates on the resolution of an individual sample, whereas `drwav_read_pcm_frames_s16()` operates on the resolution of a PCM frame. All of my libraries now operate on the resolution of a PCM frame rather than individual samples.

dr_wav does not include a reading API for unsigned 8 bit integer samples. You would need to use one of the other drwav_read_pcm_frames_*() functions and then convert, or use `drwav_read_raw()`  which just reads raw audio data from the wav file exactly as-is without any conversion.

**Comment by ScrappyCocco** [comment]
Thank you so much for your help
