### ISSUE TITLE
dr_wav - only assert things that you (intend to) ensure internally

### ISSUE THREAD

**Issue by bmcdonnell-ionx** [mackron/dr_libs#58]
I've reached a conclusion on an issue we [discussed previously](https://github.com/mackron/dr_libs/pull/34#issuecomment-400689771): in `drwav_uninit()`, I think this should be a runtime failure, not an `assert`.

````
        /* Validation for sequential mode. */
        if (pWav->isSequentialWrite) {
            drwav_assert(pWav->dataChunkDataSize == pWav->dataChunkDataSizeTargetWrite);
        }
````

You're imposing an `assert` on the client, which they may not check for.

If the application wants to abort the write, how are they supposed to cleanup?

More broadly, I *think* the rule of thumb should be as stated in this issue title. IDK if there are other instances, potentially outside of dr_wav.

https://www.beningo.com/tips-and-tricks-when-to-assert-or-not-assert/

**Comment by bmcdonnell-ionx** [comment]
Adding a return code to `drwav_uninit()` should maintain source compatibility with the library (legacy client code will ignore it), but probably not binary compatibility.

**Comment by mackron** [comment]
I'm satisfied with your rationale on this and am happy to remove that assert.

One of the mistakes I made with dr_wav was using a boolean result status instead of a result code. I'm wondering if I should start migrating towards result codes, starting with uninit()...

**Comment by bmcdonnell-ionx** [comment]
Sounds good to me. Consider making enums for your return codes, instead of `#define`s.

**Comment by mackron** [comment]
This has been fixed in the "wav/dev" branch and will be released soon. Commit: https://github.com/mackron/dr_libs/commit/c7a7342666a020a6b7aea3c8e1c719205823e5c1
