### ISSUE TITLE
use standard datatypes?

### ISSUE THREAD

**Issue by bmcdonnell-ionx** [mackron/dr_libs#59]
Low priority.

Are the `dr*_*int*` and `dr*_bool*` types necessary? Why not just use `stdint.h`, and `stdbool.h`, and if some user is using a compiler that doesn't have those, they can just make their own?

https://stackoverflow.com/questions/25461/interfacing-with-stdbool-h-c

OTOH, if you wanted to use the `c`-prefix headers (e.g. `cstdint`) in C++, the safest way to do that would be e.g.

````
#ifdef __cplusplus
    #include <cstdint>
    #include <cstddef>

    typedef std::int8_t      drwav_int8;
    // ... etc
#else
    #include <stdint.h>
    #include <stdbool.h>
    #include <stddef.h>

    typedef int8_t           drwav_int8;
    // ... etc
#endif
````

You'd still use `bool` with no additional `typedef` for both.

https://stackoverflow.com/questions/13642827/cstdint-vs-stdint-h/13643019#13643019

**Comment by mackron** [comment]
Not a fan of this suggestion, sorry. What's the actual practical problem with the current system?

> Why not just use stdint.h, and stdbool.h, and if some user is using a compiler that doesn't have those, they can just make their own?

All of my single file libraries have a policy that they should just work regardless of the compiler. My response to this is why _not_ support those compilers out of the box? Keep in mind that dr_wav has explicit support for C89 which I think may have implications regarding the availability of `stdint.h`.

> OTOH, if you wanted to use the c-prefix headers (e.g. cstdint) in C++, the safest way to do that would be e.g.

What makes this safer? The possibility that `stdint.h` isn't defined by the C++ compiler? Then I'll fix it when the community reports it as an actual real-world problem.

With the boolean thing, I like them to be of an explicit size rather than a compiler-defined size.

**Comment by bmcdonnell-ionx** [comment]
I see what you're saying.

> What's the actual practical problem with the current system?

Just a bit clutter, and a deviation from the norm.

> All of my single file libraries have a policy that they should just work regardless of the compiler. My response to this is why _not_ support those compilers out of the box? Keep in mind that dr_wav has explicit support for C89 which I think may have implications regarding the availability of `stdint.h`.

I guess I'm not a fan of bothering to maintain C89 support. The value of doing so isn't clear to me.

If I were doing my own projects with e.g. an old version of Visual Studio, I think I'd provide stdint in the projects. (Here is a [public domain example](https://snipplr.com/view/18199/stdinth/).)

But then again I'm not as big personally on the single file library approach, either. (I get it, though. I'm not suggesting you do differently.)

> > OTOH, if you wanted to use the c-prefix headers (e.g. cstdint) in C++, the safest way to do that would be e.g.
> 
> What makes this safer? The possibility that `stdint.h` isn't defined by the C++ compiler? Then I'll fix it when the community reports it as an actual real-world problem.

Safer compared to using `cstdint` (etc) for C++ and assuming that the types will be in the global namespace, which is (almost?) always the case, but not guaranteed by the standards. So to cover those possibilities and take the purist approach, you'd wind up with something that looks similar to what you already have.

> With the boolean thing, I like them to be of an explicit size rather than a compiler-defined size.

I see [you are correct](https://stackoverflow.com/questions/4897844/is-sizeofbool-defined-in-the-c-language-standard/4897859#4897859) that it's implementation defined.

Why 32?

**Comment by mackron** [comment]
No particular reason for using the 32 bit version. I think I started using it in another project for alignment purposes in a structure or something and I just kept using out of habbit.

**Comment by bmcdonnell-ionx** [comment]
If you're ever breaking things or revamping, I feel like 8-bit makes a little more sense, but it's not worth changing and breaking just that.
