### ISSUE TITLE
dr_wav: API inconsistent - samples vs. frames

### ISSUE THREAD

**Issue by bmcdonnell-ionx** [mackron/dr_libs#60]
Per dr_wav.h,

> Version 0.9.0 deprecated the per-sample reading and seeking APIs and replaced them with versions that work on the resolution of a PCM frame instead.
> ...
>     `drwav_write()                    -> drwav_write_pcm_frames()`
> ...

However, several apparently not deprecated functions take a `totalSampleCount` parameter, not `framesToWrite`. So far, I see that includes `drwav_init_write__internal()`, and all of the functions that call it and pass through `totalSampleCount`. (Generally the `*_sequential` ones.)

It also includes the new/proposed `drwav_target_write_size_bytes()` in https://github.com/mackron/dr_libs/pull/56.

**Comment by mackron** [comment]
Yes, totalSampleCount will be removed as well which I think will clean all of that up.

**Comment by bmcdonnell-ionx** [comment]
Does this part

> `Below is a list of APIs that have been deprecated and their replacements.`
> ...
> `    drwav::totalSampleCount          -> drwav::totalPCMFrameCount`

mean that these

````c
drwav_bool32 drwav_init_write_sequential       (..., drwav_uint64 totalSampleCount, ...);
drwav_bool32 drwav_init_file_write_sequential  (..., drwav_uint64 totalSampleCount);
drwav_bool32 drwav_init_memory_write_sequential(..., drwav_uint64 totalSampleCount);
drwav*       drwav_open_write_sequential       (..., drwav_uint64 totalSampleCount, ...);
````

will change to this

````c
drwav_bool32 drwav_init_write_sequential       (..., drwav_uint64 totalPCMFrameCount, ...);
drwav_bool32 drwav_init_file_write_sequential  (..., drwav_uint64 totalPCMFrameCount);
drwav_bool32 drwav_init_memory_write_sequential(..., drwav_uint64 totalPCMFrameCount);
drwav*       drwav_open_write_sequential       (..., drwav_uint64 totalPCMFrameCount, ...);
````

with no name change to the functions? (Unlike all the `{read,write}_pcm_frames` functions.)

If so, is that an acceptable disruption for any users?

**Comment by mackron** [comment]
Oh I see what you're talking about now. No, I won't be changing those as they will cause a lot of frustrating bugs. I may add "pcm_frames" variants, though. Haven't reall

**Comment by mackron** [comment]
(Accidentally tapped on my phone at the wrong moment and closed the issue. Reopened :))

**Comment by mackron** [comment]
I've added "pcm_frames" variants of these APIs to the "dev/wav" branch. Commit: https://github.com/mackron/dr_libs/commit/53d2e8695ee9e0ea03e44020f999c6bf9fe530e6
