### ISSUE TITLE
dr_flac SSE2 type error when building under Github's CI chain, amd64, Ubuntu 18.04.1, gcc 7.4.0

### ISSUE THREAD

**Issue by krcroft** [mackron/dr_libs#63]
See Line 861 here - https://github.com/dreamer/dosbox-staging/commit/a4563e66636a85254f05891441cd350511fb61a7/checks

This appears to be using the SSE2 functions. 

```
dr_flac.h: In function ‘drflac_read_pcm_frames_s16__decode_left_side__sse2’:
dr_flac.h:8243:60: warning: implicit declaration of function ‘drflac__mm_packs_interleaved_epi32’ [-Wimplicit-function-declaration]
         _mm_storeu_si128((__m128i*)(pOutputSamples + i*8), drflac__mm_packs_interleaved_epi32(left, right));
                                                            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
dr_flac.h:8243:60: error: incompatible type for argument 2 of ‘_mm_storeu_si128’
In file included from dr_flac.h:1052:0,
                 from flac.c:47:
/usr/lib/gcc/x86_64-linux-gnu/7/include/emmintrin.h:719:1: note: expected ‘__m128i {aka __vector(2) long long int}’ but argument is of type ‘int’
 _mm_storeu_si128 (__m128i_u *__P, __m128i __B)
 ^~~~~~~~~~~~~~~~

```
(and following lines).

I unfortunately can't reproduce this on my own Linux system (Ubuntu 19.04) using gcc-7.4.0; it builds clean.  My Skylake system might be using newer instructions and not taking the SSE2 code-path in dr_flac.

We can add commands to github's CI commands to help diagnose this, like dumping /proc/cpuinfo, uname -a, etc.. ); just let me know.

**Comment by dreamer** [comment]
I am experiencing the same issue on Haswell (using GCC 9.2 on Fedora 30).

**Comment by mackron** [comment]
What version of dr_flac are you using? I remember this error in my own internal testing, but I fixed that - I was incorrectly guarding this against SSE4.1 instead of SSE2. See this commit for the fix: https://github.com/mackron/dr_libs/commit/28e47b70b0cd3bb5eae1d3725e28cecaec608e7b#diff-b6781eaba35eea3e3792b1aa07e9012bL3183

Could you confirm you're on the most recent version that I pushed to the master branch a few days ago?

**Comment by krcroft** [comment]
That was it Dave, I was just behind. After checking in the latest 0.12.0 version and removing the SIMD disablement, the code compiled clean across the board.

Thank you for the quick pointer!
