### ISSUE TITLE
dr_wav: need help decoding on big-endian architecture

### ISSUE THREAD

**Issue by krcroft** [mackron/dr_libs#66]
Hi Dave, 
Looking for some tips on how to get usable signed 16-bit output on a big-endian machine from dr_wav. Right now I get what sounds like static, garbage, or possibly byte-swapped data.

I'm using an up-to-date Ubuntu-ppc Linux distro, building with gcc 5.4.x, on a big-endian PowerMac G4 with a PowerPC-7400 CPU. Of note is that dr_mp3 and dr_flac both work flawless on this machine using their respective `drmp3_read_pcm_frames_s16(...)` and `drflac_read_pcm_frames_s16(...)` functions.

The WAV file was created on an x86_64 machine and is a typical CD-rip: 44.1 kHz, 2 channels, and 16-bit samples. Decoding it with dr_wav on an x86_64 machine works great using `drwav_read_pcm_frames_s16(...)` and treating the data as least-significant-byte first.

On the PowerMac, I've tried `drwav_read_pcm_frames_s16` and `drwav_read_raw`, and I've tried treating those resulting 2-byte samples as litte, big, and system-endian: all of them play as harsh static.  

I'm wondering if the two-byte values need to be byte-swapped? Is that something dr_wav can do as part of the multi-byte 32 and 16 bit read functions when operating under big-endian? Or do you suspect something else?

**Comment by mackron** [comment]
I've never tested this on big-endian architectures, but I'm happy to fix it if you're open to testing (I don't have a big-endian machine to test on). Internally it just reads the raw data straight from the file without any conversion so I'm not surprised it's not working. I think off the top of my head this applies to both the raw audio data and all of the header information (format info, sample counts, etc.)

**Comment by mackron** [comment]
If it's possible, are you able to inspect the `drwav` object and post the state of all of it's members here? I want to eliminate the possibility that it's perhaps not converting something in the header section properly. It's strange that it doesn't work after manually byte swapping the audio data after calling `drwav_read_pcm_frames_s16()`. I assume the underlying file is also 16-bit? Is `drwav_init()` returning an error, and is `drwav_read_pcm_frames_s16()` returning the number of PCM frames you would expect?

**Comment by bmcdonnell-ionx** [comment]
I'd be happy to have dr_wav do the conversion, but in a way I'm not sure how much sense it makes. What would you do when the data is 24-bit?

**Comment by krcroft** [comment]
> It's strange that it doesn't work after manually byte swapping the audio data after calling drwav_read_pcm_frames_s16()

Oh, I haven't tried that yet. I've only tried reading the data as properly 'ramping' little or big endian values (which I suspect would have worked if my wav samples were only 8bit).   But the multi-bytes values will still be broken.

> I assume the underlying file is also 16-bit?
Yes

> Is drwav_init() returning an error, and is drwav_read_pcm_frames_s16() returning the number of PCM frames you would expect?
Surprisingly yes; DWAV_TRUE and certainly positive and large quantity of pcm frames read, although I've been killing it immediately when I hear the garbage noise.. I haven't yet compared number of expected samples versus on a little-endian machine.

> If it's possible, are you able to inspect the drwav object and post the state of all of it's members here?
Will do, and can call and particular debug or dump functions you may suggest as well.

**Comment by krcroft** [comment]
> I'd be happy to have dr_wav do the conversion, but in a way I'm not sure how much sense it makes. What would you do when the data is 24-bit?

After reading each PCM trio of bytes from file, you would then pack them into a native 32bit int or float type by swaping the first byte with the last, and then positioning the three bytes at back of the the 32 bit value's memory space.  I'm just thinking out loud.  
We also have dr_flac which is doing everything right on big endian, and it can store 24bit samples (although I've only tested so far with 16bit samples; I suppose I should try decoding a 24bit flac next on this big endian machine!)

**Comment by bmcdonnell-ionx** [comment]
If you do implement conversion, I'd suggest *not* basing the decision on whether to do it based on detected endianness of the platform. Data may come from or go to other sources having an endianness that differs from the platform, e.g. a file, serial bus, or whatever other kind of data stream.

**Comment by bmcdonnell-ionx** [comment]
Or maybe not *just* that. I haven't completely thought it through, either.

**Comment by krcroft** [comment]
I'm not sure it's a matter of **_if_** conversion is implemented; I believe it's necessary to return correct content inside data types greater than 8 bits. For example, if dr_wav offers reading PCM samples into signed 16bit variables or 32bit float variables - then those values had better be correct, regardless of what machine you're running on.

The do-nothing/won't fix approach here would involving getting rid of those int and float readers in favour of exclusively using the raw reader.  Throw back a sequence of 8bit values, and let the user-side byte-swap, invert the endianness, and pack the bytes into higher-order values as needed (which is certainly an option, but certainly not what anyone would want).

Regarding the decision on whether to do it based on detected endianness of the platform: to populate proper ints and floats, you absolutely need to know what architecture the code is running on.  Once you have that, you can always return the correct number. You also need to know how the file is written (in this case, the WAV spec says that files are always little-endian, regardless if it's written on a big-endian machine).  

Once you have ints and floats with expected values, you can then do more work with them like you noted.

**Comment by bmcdonnell-ionx** [comment]
@krcroft, looks like you're mostly if not entirely correct in your latest post. I had been using `DR_WAV_NO_CONVERSION_API`, so I wasn't as familiar with the use cases you're referring to.

I think any changes like you're talking about should only affect the `CONVERSION_API` functions, not the raw functions, so it shouldn't interfere with the use cases I was thinking of. Please someone correct me if I'm wrong.

> **Edit:** I just read this post - https://stackoverflow.com/questions/24151973/reading-24-bit-samples-from-a-wav-file Sounds like the WAV file format doesn't really support 24bit samples (as a packed 3-byte union like I mentioned above) and instead stores 32bit values.

No, you've misunderstood something. I have written 24-bit (integer) WAV files with dr_wav, and played them back with audio players. And there is the expected ~25% space savings compared to 32-bit.

It's the *processors* that don't support 3-byte int types, not the WAV format.

**Comment by mackron** [comment]
WAV files are explicitly little-endian. There's a big endian version but dr_wav doesn't support it. 24-bit WAV files are tightly packed. I won't be changing anything with drwav_read_raw(), but I'll do a byte swap on big-endian architectures in the higher level read APIs. I'll work on this.

**Comment by krcroft** [comment]
@bmcdonnell-ionx, ahh, thank you for pointing out our differing use of the conversion API!  If you're using raw bytes, then I now agree with your suggestion about leaving them as is.  We are both in agreement over our use cases :-)
Also, thanks for pointing out the file format indeed supports packed 24-bit samples (which is great) and the inflation to 32bits is on the software/processing side.  Makes sense, and is probably more efficient CPU-wise. 
@mackron I should have the dr structures ready soon.  The build takes a bit over an hour on this machine. I'm mounting the same .wav over NFS to be sure the exact file is read on both the big and small endian hosts.

**Comment by mackron** [comment]
No rush on that. This'll be a weekend job.

**Comment by krcroft** [comment]
Roger that!

**Comment by krcroft** [comment]
DRWAV_TRUE returned on both machines when opening the same stream.
The PowerPC drwav structure content matches the x86's identically except for pointer locations.
So far all looks healthy in terms of drwav doing the right thing on big-endian when parsing and opening the stream.
[drwav_powerpc.txt](https://github.com/mackron/dr_libs/files/3683789/drwav_powerpc.txt)
[drwav_x86.txt](https://github.com/mackron/dr_libs/files/3683790/drwav_x86.txt)

Here's the diff:
iff drwav_x86.txt drwav_powerpc.txt 
```
11c11
< Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
---
> Using host libthread_db library "/lib/powerpc-linux-gnu/libthread_db.so.1".
16c16
< Thread 1 "dosbox" hit Breakpoint 1, WAV_open (sample=0x35f4ce0, ext=<optimized out>) at wav.c:100
---
> Thread 1 "dosbox" hit Breakpoint 1, WAV_open (sample=0x12071920, ext=<optimized out>) at wav.c:100
21c21
<   onRead = 0x5f57ea <wav_read>, 
---
>   onRead = 0x1023df94 <wav_read>, 
23,24c23,24
<   onSeek = 0x5f5848 <wav_seek>, 
<   pUserData = 0x35f4ce0, 
---
>   onSeek = 0x1023e044 <wav_seek>, 
>   pUserData = 0x12071920, 
```

**Comment by mackron** [comment]
I've pushed a potential fix for this to the wav/dev branch: 19664257557cc55433e16472ae048cb52145bc37

**Comment by bmcdonnell-ionx** [comment]
> I've pushed a potential fix for this to the wav/dev branch: [1966425](https://github.com/mackron/dr_libs/commit/19664257557cc55433e16472ae048cb52145bc37)

Questions/comments:

1. The block comment above the `drwav_read_pcm_frames()` declaration says,

    > Reads a chunk of audio data in the native internal format.

    If by "native internal format" you mean the WAV format, thus always little endian, then this is no longer true. Please clarify and/or correct.

2. Looks like you're supporting this swap feature for reading only, but not writing? Shouldn't it be 2-way?

3. What if I'm moving the PCM data from the WAV file to a datastream (or vice versa), where the other datastream has words in big endian order, on a little endian platform? (This has happened to me, and is a reason why I'm not using this library in a project.) _Can you expose a manual control for the swapping?_ User-controllable, dynamic / on-demand.

**Comment by mackron** [comment]
@krcroft Just letting you know that I pushed a breaking API change. If you were wanting to test this, you'll just to need to add `NULL` as the last parameter to your `drwav_init*()` call(s). Hopefully I didn't break anything with that change...

@bmcdonnell-ionx 
> If by "native internal format" you mean the WAV format, thus always little endian, then this is no longer true.

c42ac66c143442f99db0e4a703b750f456d4d361

> Looks like you're supporting this swap feature for reading only, but not writing? Shouldn't it be 2-way?

be299c757b4df690294eb1ea4ac19f46b0a4dcc4 (untested)

> What if I'm moving the PCM data from the WAV file to a datastream (or vice versa), where the other datastream has words in big endian order, on a little endian platform?

If I'm understanding your question properly, that would be the same as any other data - you would check whether or not your architecture is different from the streams defined byte order and byte swap if necessary. I don't see why dr_wav should be responsible for dealing with this.

> Can you expose a manual control for the swapping? User-controllable, dynamic / on-demand.

Do you mean something like a `drwav_read_pcm_frames_be()` which reads data in a specific endianness? I'll consider it.

**Comment by krcroft** [comment]
Dropped in the latest update, added the 8th argument at NULL to init_ex(...). 
I get a clean init with DRWAVE_TRUE returned.
Reading s16 returns:
```
dosbox: dr_wav.h:1311: drwav__bswap_samples_pcm: Assertion `0' failed.
Aborted
```
Audio track spec is, `file track2.wav`:
```
cd/audio/track02.wav: RIFF (little-endian) data, WAVE audio, Microsoft PCM, 16 bit, stereo 44100 Hz
```
That was with gcc-5.4; I'm rerunning the debug build with gcc 9.2 and will dump the sampleCount and bytesPerSample upon entry into the drwav__bswap_samples_pcm function.  I'll also get another dump of the drwav struct.

**Comment by mackron** [comment]
Hmm, it's hitting the unsupported format assert here:
```c
    switch (bytesPerSample)
    {
        case 16:    /* s16 */
        {
            drwav__bswap_samples_s16(pSamples, sampleCount);
        } break;
        case 24:    /* s24 */
        {
            drwav__bswap_samples_s24(pSamples, sampleCount);
        } break;
        case 32:    /* s32 */
        {
            drwav__bswap_samples_s32(pSamples, sampleCount);
        } break;
        default:
        {
            /* Unsupported format. */
            DRWAV_ASSERT(DRWAV_FALSE);
        } break;
    }
```
The `bytesPerSample` variable is calculated like this `bytesPerFrame/pWav->channels`, so I'm wondering if `pWav->channels` is too big, thus causing that integer division to truncate to 0.

**Comment by mackron** [comment]
Oh, I'm stupid. I'm treating it as bits per sample instead of bytes per sample. Doh!

**Comment by krcroft** [comment]
You beat me too it, and blind without an actual machine no less! :-)  I just finished dumping the values in gdb and came here report I'm getting a 2 instead of 16 for bytesPerSample (I made the edit and the decode now works flawlessly!).  

I will pull the update and confirm.

**Comment by krcroft** [comment]
Latest source is decoding perfectly on my PowerPC 7400, and it compiles warning-free using gcc 5.4.x and 9.2.x on big-endian as well.  Thank you!

**Comment by bmcdonnell-ionx** [comment]
> > What if I'm moving the PCM data from the WAV file to a datastream (or vice versa), where the other datastream has words in big endian order, on a little endian platform?
> 
> ... I don't see why dr_wav should be responsible for dealing with this.

Because you've already done the work of supporting swapping, it seems like an artificial restriction not to allow someone who wants to use it to do so just because because it's not the platform endianness that's making them want to swap.

> > Can you expose a manual control for the swapping? User-controllable, dynamic / on-demand.
> 
> Do you mean something like a `drwav_read_pcm_frames_be()` which reads data in a specific endianness? I'll consider it.

And `drwav_write_pcm_frames_be()`.

(More explicitly, something like `drwav_read_pcm_frames_to_be()` and `drwav_write_pcm_frames_from_be()`, but I'm not sure that's your style.)

... I'm not sure if this would facilitate me using the library in my current project, as I did the swapping myself and there were some other considerations at play. But maybe.

**Comment by krcroft** [comment]
(Reopening to support the discussion and disposition of topics suggested by @bmcdonnell-IONX)

**Comment by mackron** [comment]
When I wrote that I was initially concerned about the maintenance costs of what I felt was a niche requirement, but I've taken a look and it actually isn't as bad as I was originally thinking. There's just a minor bit of code duplication for `drwav_write_pcm_frames()`, but not the end of the world. You could argue that it's actually better for code maintenance because when you read it you can explicitly see the endianness.

In addition, I noticed libsndfile (which I use as a benchmark) also supports explicit endianness so I can at least write some automated test cases for this.

I've pushed a commit with support for reading and writing in an explicit endianness: f4b29cd655c4243de4bbe191c0ff4db14597c575

New APIs:
```
drwav_read_pcm_frames_le()
drwav_read_pcm_frames_be()
drwav_read_pcm_frames_s16le()
drwav_read_pcm_frames_s16be()
drwav_read_pcm_frames_f32le()
drwav_read_pcm_frames_f32be()
drwav_read_pcm_frames_s32le()
drwav_read_pcm_frames_s32be()
drwav_write_pcm_frames_le()
drwav_write_pcm_frames_be()
```
These haven't been fully tested yet.

**Comment by bmcdonnell-ionx** [comment]
I like the general architecture. One problem I see though is that there are some situations where you're swapping twice, whereas obviously the preferred course would be to swap 0 times. e.g. Suppose you're on a big endian platform, wanting to read s16 pcm data as little endian from a wav file already in s16 pcm format. The relevant parts of the call tree could look like this:

```
drwav_read_pcm_frames_s16le()
 - drwav_read_pcm_frames_s16()
   - e.g. drwav_read_pcm_frames_s16__pcm()
     - drwav_read_pcm_frames()
       - drwav_read_pcm_frames_be()
         - drwav_read_pcm_frames_le()
         - drwav__bswap_samples()
           - drwav__bswap_samples_pcm()
             - drwav__bswap_samples_s16()
 - drwav__bswap_samples_s16()
```

**Comment by bmcdonnell-ionx** [comment]
Also one small item I noticed: In `drwav_write_pcm_frames_be()`, I think you could factor these 2 lines out of the while loop to eliminate some redundant calculations.

```
        bytesPerSample = drwav_get_bytes_per_pcm_frame(pWav) / pWav->channels;
        sampleCount = sizeof(temp)/bytesPerSample;
```

**Comment by mackron** [comment]
> One problem I see though is that there are some situations where you're swapping twice

I'm aware of this, but I'm not changing it right now. Too much code duplication for it's value. I'm not doing BE and NE versions of `drwav_read_pcm_frames_s16__pcm/__ieee/etc()`.

**Comment by krcroft** [comment]
I will test the new explicit-endian APIs on my powerpc.

**Comment by krcroft** [comment]
Tested on both systems and working well; dr_* keeps getting better; thank you both!

**Comment by mackron** [comment]
Thanks for testing. I'll get this released.
