### ISSUE TITLE
[question] Support for ACID data in dr_wav ?

### ISSUE THREAD

**Issue by jcelerier** [mackron/dr_libs#72]
Hello,
first thanks for the great library.

Some wave files come with embedded musical information such as tempo, time signature, etc... those are stored in a special RIFF chunk with the "acid" tag. 

Would you consider giving dr_wav a way to retrieve this data ? And if not, what would be the easiest way to get there given a dr_wav structure, if possible without rewriting a whole another RIFF parser (e.g. for instance a way to go from one riff header to another easily) ? 

Thanks !

**Comment by mackron** [comment]
dr_wav has a generic way of handling all kinds of chunks. Use the _ex() variations of drwav_init(). This will let you pass in a callback that's fired for each chunk which will give you an opportunity to read and handle the chunk data however you want. See the documentation here for how to use the callback: https://github.com/mackron/dr_libs/blob/master/dr_wav.h#L422-L438

Basically how the chunk callback works is that you are provided with a pointer to a read function and a seek function and you use those to read/seek data from the chunk you're interested in. You then return the number of bytes you read+seeked (just return 0 for the chunks you aren't interested in).

Note that this will not work if you use the `DRWAV_SEQUENTIAL` flag, in which case it's not possible.

Do you have link to a specification/documentation for this ACID chunk?

**Comment by jcelerier** [comment]
Best we have is this : https://github.com/erikd/libsndfile/blob/master/src/wav.c#L1427

Your solution looks exactly like what I'm looking for, thanks !

**Comment by mackron** [comment]
Good to hear. I'll go ahead and close this, but if it doesn't work for you or you have more questions feel free to re-open it.
