### ISSUE TITLE
dr_flac: use of uninitialized header variable (Coverty scan)

### ISSUE THREAD

**Issue by krcroft** [mackron/dr_libs#73]
Hi @mackron,

I've recently started scanning the staging repo of DOSBox using Coverty, and wanted to pass on two issues flagged as 'high'. 

I've highlighted the route of conditionals to land on the issue (which is quite interesting, albeit I'm not sure if it's realistic or not!). The quick fix is to initialize `header` at line 6527.   

A second issue having the same uninitialized use is described in short-form at the bottom of this report.

```
static drflac_bool32 drflac_oggbs__goto_next_page(drflac_oggbs* oggbs, drflac_ogg_crc_mismatch_recovery recoveryMethod)
6527{
```
**1. var_decl: Declaring variable header without initializer.**
`6528    drflac_ogg_page_header header;
`
**2. Condition true, taking true branch.**
```
6529    for (;;) {
6530        drflac_uint32 crc32 = 0;
6531        drflac_uint32 bytesRead;
6532        drflac_uint32 pageBodySize;
6533#ifndef DR_FLAC_NO_CRC
6534        drflac_uint32 actualCRC32;
6535#endif
6536
```
**3. Condition drflac_ogg__read_page_header(oggbs->onRead, oggbs->pUserData, &header, &bytesRead, &crc32) != 0, taking false branch.**
```
6537        if (drflac_ogg__read_page_header(oggbs->onRead, oggbs->pUserData, &header, &bytesRead, &crc32) != DRFLAC_SUCCESS) {
6538            return DRFLAC_FALSE;
6539        }
6540        oggbs->currentBytePos += bytesRead;
6541
6542        pageBodySize = drflac_ogg__get_page_body_size(&header);
    	4. Condition pageBodySize > 65307, taking false branch.
6543        if (pageBodySize > DRFLAC_OGG_MAX_PAGE_SIZE) {
6544            continue;   /* Invalid page size. Assume it's corrupted and just move to the next page. */
6545        }
6546
```

**5. Condition header.serialNumber != oggbs->serialNumber, taking false branch.**
```
6547        if (header.serialNumber != oggbs->serialNumber) {
6548            /* It's not a FLAC page. Skip it. */
6549            if (pageBodySize > 0 && !drflac_oggbs__seek_physical(oggbs, pageBodySize, drflac_seek_origin_current)) {
6550                return DRFLAC_FALSE;
6551            }
6552            continue;
6553        }
6554
6555
6556        /* We need to read the entire page and then do a CRC check on it. If there's a CRC mismatch we need to skip this page. */
```
**6. Condition drflac_oggbs__read_physical(oggbs, oggbs->pageData, pageBodySize) != pageBodySize, taking false branch.**
```
6557        if (drflac_oggbs__read_physical(oggbs, oggbs->pageData, pageBodySize) != pageBodySize) {
6558            return DRFLAC_FALSE;
6559        }
6560        oggbs->pageDataSize = pageBodySize;
6561
6562#ifndef DR_FLAC_NO_CRC
6563        actualCRC32 = drflac_crc32_buffer(crc32, oggbs->pageData, oggbs->pageDataSize);
```
**7. Condition actualCRC32 != header.checksum, taking false branch.**
```
6564        if (actualCRC32 != header.checksum) {
6565            if (recoveryMethod == drflac_ogg_recover_on_crc_mismatch) {
6566                continue;   /* CRC mismatch. Skip this page. */
6567            } else {
6568                /*
6569                Even though we are failing on a CRC mismatch, we still want our stream to be in a good state. Therefore we
6570                go to the next valid page to ensure we're in a good state, but return false to let the caller know that the
6571                seek did not fully complete.
6572                */
6573                drflac_oggbs__goto_next_page(oggbs, drflac_ogg_recover_on_crc_mismatch);
6574                return DRFLAC_FALSE;
6575            }
6576        }
6577#else
6578        (void)recoveryMethod;   /* <-- Silence a warning. */
6579#endif
6580
```
    	
**CID 277421 (#1 of 1): Uninitialized scalar variable (UNINIT)
8. uninit_use: Using uninitialized value header. Field header. CapturePattern is uninitialized.**
```
6581        oggbs->currentPageHeader = header;
6582        oggbs->bytesRemainingInPage = pageBodySize;
6583        return DRFLAC_TRUE;
6584    }
6585}
```

A similar uninitialized `header` variable occurs when it's read on line 7022,  `pInit->oggBosHeader  = header;`.

**Comment by mackron** [comment]
Thanks for the report. I'll get onto this as soon as I can.

**Comment by krcroft** [comment]
There are others of lesser criticality (I think roughly six or seven each per codec); would you prefer I create issues against them (grouped into similar themes like this)? I could also lift out the content to text file(s), and I could attach them here.  What suits your preference! Also no rush; these are definitely corner cases.

**Comment by mackron** [comment]
Yeah feel free to go ahead and create separate issues for each project so we have a record of it. I'll hack away on them as I get to it.

**Comment by krcroft** [comment]
Sounds good; I just finished creating issues individually, and I've re-added the two I mentioned here on their own as well; so I'll close this topic here and let the other stand on their own.  Thanks again Dave.
