### ISSUE TITLE
reading YANK02.PCX with dr_pcx and writing it with stb_image_write_png results in different image

### ISSUE THREAD

**Issue by jopadan** [mackron/dr_libs#74]
Reading Comanche 3 RESOURCE.RES extract YANK02.PCX with dr_pcx and writing 
with nothings/stb stbi_write_png results in a totally different image.
https://github.com/jopadan/VoxelSpace/tree/master/tools/comanche3extract/extract.c
There are also some images which are skipped and get displayed correctly with imv
using FreeImage.

**Comment by mackron** [comment]
Why the close? Anything I need to look at?

There's a lot of cases that I've never tested due to lack of availability of sample files. Also, I've moved dr_pcx out of this repository and into its own repository. This one is now dedicated to my audio decoders.

**Comment by hanatos** [comment]
if i may comment on this.. the comanche3 pcx files aren't really pcx files, they just share the file extension and sometimes the content is pcx, sometimes not at all. code from the happy 90s i guess.
