### ISSUE TITLE
dr_flac: result in not floating-point in drflac__seek_to_pcm_frame__binary_search_internal

### ISSUE THREAD

**Issue by krcroft** [mackron/dr_libs#91]
```
5341 static drflac_bool32 drflac__seek_to_pcm_frame__binary_search_internal(drflac* pFlac, drflac_uint64 pcmFrameIndex, drflac_uint64 byteRangeLo, drflac_uint64 byteRangeHi)
5342{
5343    /* This assumes pFlac->currentPCMFrame is sitting on byteRangeLo upon entry. */
5344
5345    drflac_uint64 targetByte;
5346    drflac_uint64 pcmRangeLo = pFlac->totalPCMFrameCount;
5347    drflac_uint64 pcmRangeHi = 0;
5348    drflac_uint64 lastSuccessfulSeekOffset = (drflac_uint64)-1;
5349    drflac_uint64 closestSeekOffsetBeforeTargetPCMFrame = byteRangeLo;
5350    drflac_uint32 seekForwardThreshold = (pFlac->maxBlockSizeInPCMFrames != 0) ? pFlac->maxBlockSizeInPCMFrames*2 : 4096;
5351
    	
CID 277393 (#1 of 1): Result is not floating-point (UNINTENDED_INTEGER_DIVISION)
integer_division: Dividing integer expressions (pcmFrameIndex - pFlac->currentPCMFrame) * pFlac->channels * pFlac->bitsPerSample and 8UL, and then converting the integer quotient to type float. Any remainder, or fractional part of the quotient, is ignored.
    	To compute and use a non-integer quotient, change or cast either operand to type float. If integer division is intended, consider indicating that by casting the result to type unsigned long .
5352    targetByte = byteRangeLo + (drflac_uint64)((pcmFrameIndex - pFlac->currentPCMFrame) * pFlac->channels * pFlac->bitsPerSample/8 * DRFLAC_BINARY_SEARCH_APPROX_COMPRESSION_RATIO);
5353    if (targetByte > byteRangeHi) {
5354        targetByte = byteRangeHi;
5355    }
```

**Comment by mackron** [comment]
False positive. The division by 8 is for bit-to-byte conversion. As a potential work around for this
I have wrapped the integer component in brackets.

Commit: 2c07c5041436a5b930bced034f56247a1ac27d40

**Comment by krcroft** [comment]
Makes sense; thanks for the explicit order of operations. Thanks.

**Comment by krcroft** [comment]
Results after new scan:
``` C++
static drflac_bool32 drflac__seek_to_pcm_frame__binary_search_internal(drflac* pFlac, drflac_uint64 pcmFrameIndex, drflac_uint64 byteRangeLo, drflac_uint64 byteRangeHi)
{
    /* This assumes pFlac->currentPCMFrame is sitting on byteRangeLo upon entry. */
    drflac_uint64 targetByte;
    drflac_uint64 pcmRangeLo = pFlac->totalPCMFrameCount;
    drflac_uint64 pcmRangeHi = 0;
    drflac_uint64 lastSuccessfulSeekOffset = (drflac_uint64)-1;
    drflac_uint64 closestSeekOffsetBeforeTargetPCMFrame = byteRangeLo;
    drflac_uint32 seekForwardThreshold = (pFlac->maxBlockSizeInPCMFrames != 0) ? pFlac->maxBlockSizeInPCMFrames*2 : 4096;
CID 277393 (#1 of 1): Result is not floating-point (UNINTENDED_INTEGER_DIVISION)
integer_division: Dividing integer expressions (pcmFrameIndex - pFlac->currentPCMFrame) * pFlac->channels * pFlac->bitsPerSample and 8UL, and then converting the integer quotient to type float. Any remainder, or fractional part of the quotient, is ignored.
To compute and use a non-integer quotient, change or cast either operand to type float. If integer division is intended, consider indicating that by casting the result to type unsigned long .
    targetByte = byteRangeLo + (drflac_uint64)(((pcmFrameIndex - pFlac->currentPCMFrame) * pFlac->channels * pFlac->bitsPerSample/8) * DRFLAC_BINARY_SEARCH_APPROX_COMPRESSION_RATIO);
```

**Comment by krcroft** [comment]
It seems like it wants to be told that the result from the integer division is definitely an integer, and we're not expecting it to be a float.

**Comment by mackron** [comment]
This is annoying... I don't want to do a (unsigned long)-style cast because it looks ugly and unnecessarily verbose. I've change the "8" to "8UL" to make it more explicit.

**Comment by mackron** [comment]
Reopening this one to keep track of it's status. Any others I needed to reopen?

**Comment by krcroft** [comment]
Yeah; even with the integer denominator it's still complaining.  
Hmm.. I can try later with a simple "bits to bytes" function that takes in a const unsigned, shifts right three, and returns the result.  I think shifts inherently stay within integer-space, so maybe that will be a explicit as it gets.

**Comment by krcroft** [comment]
All others are solved; this is it!

**Comment by mackron** [comment]
Yeah I actually considered a 3-bit shift, but I don't think it's as readable for humans. If a `drflac_bits_to_bytes()` works I'll be happy to use that instead. If that doesn't work we'll just store the integer part in a variable. I don't want to to use a second cast in that line because there's already an outer `(drflac_uint64)` cast which makes things too hard to read.

Personally I think the "UL" is more than enough for the static analyser to realise it's an intentional integer division - you can't get much more explicit and deliberate than that! I think it's stupid that the analyser would flag this...

**Comment by krcroft** [comment]
I agree on all counts!

**Comment by krcroft** [comment]
> a 3-bit shift
Definitely less readable than /8 when sprinkled throughout the code. 

I think a nicely named function would help be more readable and obvious versus the /8, which may not be obvious right away. (some codecs are stereo, 2 bytes per channel, and seeing divisions by 4, 8, and 16 sprinked about isn't obvious what the intent is without digging into the surrounding context).

**Comment by mackron** [comment]
Yes, I agree, but in the context of this particular one, it's used against a variable called *bits*PerSample, which I think makes it obvious. But yes, a function is fine. Were you going to write that and test it first, or did you want me to write it?

**Comment by krcroft** [comment]
Just built and pushed to Coverity; results any minute now.
Testing with this:
``` c++
drflac_uint8 bits_to_bytes(const drflac_uint8 num_bits) {
    return num_bits >> 3;
}
```

**Comment by krcroft** [comment]
The shift-function solves it - and looks like it was OK without the extra parens from 2c07c50.

Here's what passed: `byteRangeHi = pFlac->firstFLACFramePosInBytes + (drflac_uint64)(pFlac->totalPCMFrameCount * pFlac->channels * bits_to_bytes(pFlac->bitsPerSample));`, along with similar use in all the` /8UL` lines.

Here's what I'm seeing the Coverity UI (The dr_* headers were previously in between archive.h and stb_vorbis):  
![2019-11-30_19-38](https://user-images.githubusercontent.com/1557255/69909023-0c995e80-13a9-11ea-804d-67560959db3a.png)

**Comment by mackron** [comment]
Cool. I'll go ahead and make that change.

**Comment by krcroft** [comment]
Closing this out - thanks for all the improvements Dave.

**Comment by mackron** [comment]
Reopening this, because you know what: now that I'm implementing this, I think we actually do indeed want to use floating point arithmetic for this! 🤦‍♂️ The reason is that `bitsPerSample` is not always a multiple of 8, and in the context in which we're doing this, it's to approximate a byte location for seeking. Therefore out integer division by eight will completely break for situations where `bitsPerSample` is something like 4 (which is valid in a FLAC file). If `bitsPerSample` is 4, the integer division will equate to 0 which will cause our approximate seek location to completely break down. I'm going to switch this to 8.0f like the original report suggested.

**Comment by krcroft** [comment]
Great catch; I lost sight of the purpose of the multiplication.  Win-win fix; better seek accuracy, just as lean code, and solve a flagged issue. (fascinating that warning helped too, because the remainder was being discarded this whole time).

**Comment by mackron** [comment]
Yes, it was a good report in the end. I've pushed an update for this to the flac/dev branch: https://github.com/mackron/dr_libs/commit/7243cf00a628ffa1d6ce47b1394fb52f3d3093a8

All of my automated tests have passed so once you're able to confirm that the static analyser is silenced for good I'm happy to get all of these changes merged into master.

**Comment by krcroft** [comment]
Throttled by our submission limit :-) "The build submission quota for this project has been reached. Next submission permitted on or after 2019-Dec-01 3:31 PM UTC , about 9 hours from now.". 
:hourglass_flowing_sand:

**Comment by krcroft** [comment]
Submitted and now confirmed that the floating point division solved it!

**Comment by mackron** [comment]
Thanks for verifying. All of those changes have been released now.
