### ISSUE TITLE
dr_flac: Expression 'result == - 129' is always false.

### ISSUE THREAD

**Issue by krcroft** [mackron/dr_libs#95]
![image](https://user-images.githubusercontent.com/1557255/72753538-09854800-3b7a-11ea-9efe-5a0e75d0c9db.png)

Detected during static analysis in PVS Studio.

**Comment by mackron** [comment]
This may be true now, but not necessarily in the future. Adjusting the code to silence this warning has potential safety implications and maintenance burdens so will not fix.
