### ISSUE TITLE
dr_flac: A part of conditional expression is always true: !wasSuccessful.

### ISSUE THREAD

**Issue by krcroft** [mackron/dr_libs#96]
![image](https://user-images.githubusercontent.com/1557255/72753662-5832e200-3b7a-11ea-823e-2c1d05648810.png)

https://www.viva64.com/en/w/v560/

**Comment by mackron** [comment]
Silenced in this commit (dev branch): https://github.com/mackron/dr_libs/commit/05fc91f7b604caab1bb170821e85d0d4ac1897de

**Comment by krcroft** [comment]
Thanks for the fix!
