### ISSUE TITLE
dr_mp3: The 'b / 3' expression was implicitly cast from 'int' type to 'float'

### ISSUE THREAD

**Issue by krcroft** [mackron/dr_libs#98]
![image](https://user-images.githubusercontent.com/1557255/72753796-b95ab580-3b7a-11ea-8ebe-92a08dacdb77.png)

https://www.viva64.com/en/w/v636/

**Comment by lieff** [comment]
Bug in PVS-Studio? `(1 << 21 >> b/3)` expression was implicitly cast from integer to float.

**Comment by mackron** [comment]
This is the same kind of error as this issue: https://github.com/mackron/dr_libs/issues/91. This report is misleading - it's throwing this warning because it's later used in the context of a floating point operation, which in this case is the first term in the equation (`g_deq_L12[ba*3 - 6 + b % 3]`). I _think_ changing it from
    s = g_deq_L12[ba*3 - 6 + b % 3]*(1 << 21 >> b/3);
to
    s = g_deq_L12[ba*3 - 6 + b % 3]*(int)(1 << 21 >> b/3);
might fix it, but I've not tested it or anything. Personally I'm fine with setting this to will not fix, but if @lieff want's to fix it in minimp3 I'm happy to mirror the change over here as well.

**Comment by lieff** [comment]
Or mat be even `(1 << 21 >> (b/3))` can silence it. But still looks like PVS-Studio issue, because it's not integer a/b in float context pattern. There integer shift operation depends on a/b, so no any precision loss later in float context which depends on a/b.

**Comment by mackron** [comment]
@krcroft I've done an experimental fix for this one. This uses @lieff's suggestion and just wraps the `b/3` section in parenthesis. However, if this is anything like issue #91 I don't think it'll work. If this doesn't work I'll try the explicit cast to int. This is in the mp3/dev branch.

**Comment by krcroft** [comment]
Thanks @mackron; will give this a try come morning and report back.

**Comment by krcroft** [comment]
https://github.com/dreamer/dosbox-staging/suites/419629906/artifacts/1333199

![2020-01-24_20-20](https://user-images.githubusercontent.com/1557255/73116197-1641cd00-3ee7-11ea-9038-df789536c4b7.png)

**Comment by mackron** [comment]
I've pushed another attempt with an explicit cast. If this one doesn't I'm just going to set this one to Will Not Fix.

https://github.com/mackron/dr_libs/commit/005004bc96835cf9d3545b6e2f1d38d55700df25

**Comment by krcroft** [comment]
That's fixed it; thank you!

**Comment by lieff** [comment]
May be it's worth reporting this to viva64. I showed the issue to other people and they all agree that it's a bug in PVS-Studio.
I did not find any PVS-Studio bug tracker, only support via support@viva64.com .
https://www.viva64.com/en/m/0029/

>If it seems to you that the analyzer fails to find errors in a code fragment that surely contains them or, on the contrary, generates false positives for a code fragment which you believe to be correct, please send us the preprocessor's temporary file. You can get it by setting the 'PVS-Studio -> Options -> Common Analyzer Settings -> Remove Intermediate Files' option to 'False'.

**Comment by mackron** [comment]
I also think it should be considered a false positive, however for the purpose of dr_mp3 I'm happy enough to throw the cast in there and move on.

**Comment by krcroft** [comment]
@lieff , thanks for the digging up their support details.  I will pass it onto them and see what they think; maybe there's something interesting or subtle (I'm not sure what or why though) as to why this statement is flagged but countless others of similar float * int are not. 

@mackron , thanks.

**Comment by mackron** [comment]
I'd say it's because of the higher level context where it's later used in a float * int. It's just like that other warning from dr_flac where it ended up being an actual bug in my code.

These changes will be released soon. Closing.
