### ISSUE TITLE
dr_mp3: Consider inspecting the 'for' operator.

### ISSUE THREAD

**Issue by krcroft** [mackron/dr_libs#99]
![image](https://user-images.githubusercontent.com/1557255/72753856-ead38100-3b7a-11ea-8926-e48f44d84a66.png)

https://www.viva64.com/en/w/v1008/

**Comment by lieff** [comment]
But not in case HAVE_SIMD=0. Any idea how properly silence it without copy-paste code in HAVE_SIMD=1 case?

**Comment by krcroft** [comment]
@lieff , maybe something like this:

``` c++
        si[5] = -si[5];
        si[7] = -si[7];

#if DRMP3_HAVE_SIMD
        if (drmp3_have_simd()) for (i=0; i < 8; i += 4)
        {
            drmp3_f4 vovl = DRMP3_VLD(overlap + i);
            drmp3_f4 vc = DRMP3_VLD(co + i);
            drmp3_f4 vs = DRMP3_VLD(si + i);
            drmp3_f4 vr0 = DRMP3_VLD(g_twid9 + i);
            drmp3_f4 vr1 = DRMP3_VLD(g_twid9 + 9 + i);
            drmp3_f4 vw0 = DRMP3_VLD(window + i);
            drmp3_f4 vw1 = DRMP3_VLD(window + 9 + i);
            drmp3_f4 vsum = DRMP3_VADD(DRMP3_VMUL(vc, vr1), DRMP3_VMUL(vs, vr0));
            DRMP3_VSTORE(overlap + i, DRMP3_VSUB(DRMP3_VMUL(vc, vr0), DRMP3_VMUL(vs, vr1)));
            DRMP3_VSTORE(grbuf + i, DRMP3_VSUB(DRMP3_VMUL(vovl, vw0), DRMP3_VMUL(vsum, vw1)));
            vsum = DRMP3_VADD(DRMP3_VMUL(vovl, vw1), DRMP3_VMUL(vsum, vw0));
            DRMP3_VSTORE(grbuf + 14 - i, DRMP3_VREV(vsum));
        }
#else
        for (i=0; i < 9; i++)
#endif
       {
            float ovl  = overlap[i];
            float sum  = co[i]*g_twid9[9 + i] + si[i]*g_twid9[0 + i];
            overlap[i] = co[i]*g_twid9[0 + i] - si[i]*g_twid9[9 + i];
            grbuf[i]      = ovl*window[0 + i] - sum*window[9 + i];
            grbuf[17 - i] = ovl*window[9 + i] + sum*window[0 + i];
        }
 ```

**Comment by lieff** [comment]
Nope, have_simd() may be false and we need 9 non-simd iterations in that case.

**Comment by krcroft** [comment]
Hmm; so `DRMP3_HAVE_SIMD` can be set, but `drmp3_have_simd()` return false?

#if DRMP3_HAVE_SIMD
        if (drmp3_have_simd())
                for (i=0; i < 8; i += 4)
                { ... }
        else
                for (i=0; i < 9; i++)
#else
        for (i=0; i < 9; i++)
#endif
        { ... }

**Comment by lieff** [comment]
^ still fails, in drmp3_have_simd()==true case last non-sind iteration omitted.

>Hmm; so DRMP3_HAVE_SIMD can be set, but drmp3_have_simd() return false?

Yes, for 32-bit it`s checked using cpuid instuction.

**Comment by krcroft** [comment]
> ^ still fails, in drmp3_have_simd()==true case last non-simd iteration omitted.

The block after last `#endif` will perform the final iteration.
`drmp3_have_simd()==true`, SIMD loops finish and leaves `i == 8`.  Skips the `else` and `#else`, then enters this block with i = 8 (performing the last final pass):

 ``` c++
#endif
       {
            float ovl  = overlap[i];
            float sum  = co[i]*g_twid9[9 + i] + si[i]*g_twid9[0 + i];
            overlap[i] = co[i]*g_twid9[0 + i] - si[i]*g_twid9[9 + i];
            grbuf[i]      = ovl*window[0 + i] - sum*window[9 + i];
            grbuf[17 - i] = ovl*window[9 + i] + sum*window[0 + i];
        }
```

**Comment by lieff** [comment]
It's attached to `else for (i=0; i < 9; i++)`
Code after pre-processor.
{code}
        if (drmp3_have_simd())
                for (i=0; i < 8; i += 4)
                { ... }
        else
                for (i=0; i < 9; i++)
        { ... }
{code}

**Comment by krcroft** [comment]
Good catch; hmm.  The puzzle deepens :-)

**Comment by lieff** [comment]
Yep )

**Comment by krcroft** [comment]
I suggest a `wont fix` for this, and silence it via exclusion.  There is no bug here, and satisfying the analyzer is going to harm it's readability.

**Comment by lieff** [comment]
Yes, do not see good solution either.
